// Generated by stayputnik-codegen. Do not edit.

use crate::codec::{self, Decode, Encode};

/// A Docking Camera.
///
/// A remote object handle for a `DockingCamera.Camera` instance.
#[derive(Debug, Clone)]
pub struct Camera {
    client: crate::ClientRef,
    pub(crate) id: u64,
}

impl Camera {
    pub(crate) fn new(client: crate::ClientRef, id: u64) -> Self {
        Self { client, id }
    }

    /// The id of the remote object this handle refers to.
    pub fn object_id(&self) -> u64 {
        self.id
    }

    /// Get the image.
    pub async fn image(&self) -> crate::Result<Vec<u8>> {
        let data = self.client.invoke("DockingCamera", "Camera_get_Image", &[codec::arg(0, &self.id)]).await?;
        Decode::decode_krpc(&self.client, &data)
    }

    /// Get the part containing this Camera.
    pub async fn part(&self) -> crate::Result<super::space_center::Part> {
        let data = self.client.invoke("DockingCamera", "Camera_get_Part", &[codec::arg(0, &self.id)]).await?;
        Decode::decode_krpc(&self.client, &data)
    }
}

impl PartialEq for Camera {
    fn eq(&self, other: &Self) -> bool {
        self.id == other.id
    }
}

impl Eq for Camera {}

impl std::hash::Hash for Camera {
    fn hash<H: std::hash::Hasher>(&self, state: &mut H) {
        self.id.hash(state);
    }
}

impl Encode for Camera {
    fn encode_krpc(&self) -> Vec<u8> {
        self.id.encode_krpc()
    }
}

impl Decode for Camera {
    fn decode_krpc(client: &crate::ClientRef, bytes: &[u8]) -> crate::Result<Self> {
        let id = <u64 as Decode>::decode_krpc(client, bytes)?;
        Ok(Self::new(client.clone(), id))
    }
}

impl Decode for Option<Camera> {
    fn decode_krpc(client: &crate::ClientRef, bytes: &[u8]) -> crate::Result<Self> {
        let id = <u64 as Decode>::decode_krpc(client, bytes)?;
        Ok(if id == 0 { None } else { Some(Camera::new(client.clone(), id)) })
    }
}

/// Camera Service
pub struct DockingCamera {
    client: crate::ClientRef,
}

impl DockingCamera {
    pub fn new(client: crate::ClientRef) -> Self {
        Self { client }
    }

    /// Check if the Camera API is avaiable
    pub async fn available(&self) -> crate::Result<bool> {
        let data = self.client.invoke("DockingCamera", "get_Available", &[]).await?;
        Decode::decode_krpc(&self.client, &data)
    }

    /// Get a Camera part
    pub async fn camera(&self, part: &super::space_center::Part) -> crate::Result<Camera> {
        let data = self.client.invoke("DockingCamera", "Camera", &[codec::arg(0, &part)]).await?;
        Decode::decode_krpc(&self.client, &data)
    }
}
