// Generated by stayputnik-codegen. Do not edit.

use crate::codec::{self, Decode, Encode};

/// A line. Created using `Drawing.AddLine`.
///
/// A remote object handle for a `Drawing.Line` instance.
#[derive(Debug, Clone)]
pub struct Line {
    client: crate::ClientRef,
    pub(crate) id: u64,
}

impl Line {
    pub(crate) fn new(client: crate::ClientRef, id: u64) -> Self {
        Self { client, id }
    }

    /// The id of the remote object this handle refers to.
    pub fn object_id(&self) -> u64 {
        self.id
    }

    /// Set the color
    pub async fn color(&self) -> crate::Result<(f64, f64, f64)> {
        let data = self.client.invoke("Drawing", "Line_get_Color", &[codec::arg(0, &self.id)]).await?;
        Decode::decode_krpc(&self.client, &data)
    }

    /// End position of the line.
    pub async fn end(&self) -> crate::Result<(f64, f64, f64)> {
        let data = self.client.invoke("Drawing", "Line_get_End", &[codec::arg(0, &self.id)]).await?;
        Decode::decode_krpc(&self.client, &data)
    }

    /// Material used to render the object. Creates the material from a shader with the given name.
    pub async fn material(&self) -> crate::Result<String> {
        let data = self.client.invoke("Drawing", "Line_get_Material", &[codec::arg(0, &self.id)]).await?;
        Decode::decode_krpc(&self.client, &data)
    }

    /// Reference frame for the positions of the object.
    pub async fn reference_frame(&self) -> crate::Result<super::space_center::ReferenceFrame> {
        let data = self.client.invoke("Drawing", "Line_get_ReferenceFrame", &[codec::arg(0, &self.id)]).await?;
        Decode::decode_krpc(&self.client, &data)
    }

    /// Start position of the line.
    pub async fn start(&self) -> crate::Result<(f64, f64, f64)> {
        let data = self.client.invoke("Drawing", "Line_get_Start", &[codec::arg(0, &self.id)]).await?;
        Decode::decode_krpc(&self.client, &data)
    }

    /// Set the thickness
    pub async fn thickness(&self) -> crate::Result<f32> {
        let data = self.client.invoke("Drawing", "Line_get_Thickness", &[codec::arg(0, &self.id)]).await?;
        Decode::decode_krpc(&self.client, &data)
    }

    /// Whether the object is visible.
    pub async fn visible(&self) -> crate::Result<bool> {
        let data = self.client.invoke("Drawing", "Line_get_Visible", &[codec::arg(0, &self.id)]).await?;
        Decode::decode_krpc(&self.client, &data)
    }

    /// Set the color
    pub async fn set_color(&self, value: (f64, f64, f64)) -> crate::Result<()> {
        self.client.invoke("Drawing", "Line_set_Color", &[codec::arg(0, &self.id), codec::arg(1, &value)]).await?;
        Ok(())
    }

    /// End position of the line.
    pub async fn set_end(&self, value: (f64, f64, f64)) -> crate::Result<()> {
        self.client.invoke("Drawing", "Line_set_End", &[codec::arg(0, &self.id), codec::arg(1, &value)]).await?;
        Ok(())
    }

    /// Material used to render the object. Creates the material from a shader with the given name.
    pub async fn set_material(&self, value: &str) -> crate::Result<()> {
        self.client.invoke("Drawing", "Line_set_Material", &[codec::arg(0, &self.id), codec::arg(1, &value)]).await?;
        Ok(())
    }

    /// Reference frame for the positions of the object.
    pub async fn set_reference_frame(&self, value: &super::space_center::ReferenceFrame) -> crate::Result<()> {
        self.client.invoke("Drawing", "Line_set_ReferenceFrame", &[codec::arg(0, &self.id), codec::arg(1, &value)]).await?;
        Ok(())
    }

    /// Start position of the line.
    pub async fn set_start(&self, value: (f64, f64, f64)) -> crate::Result<()> {
        self.client.invoke("Drawing", "Line_set_Start", &[codec::arg(0, &self.id), codec::arg(1, &value)]).await?;
        Ok(())
    }

    /// Set the thickness
    pub async fn set_thickness(&self, value: f32) -> crate::Result<()> {
        self.client.invoke("Drawing", "Line_set_Thickness", &[codec::arg(0, &self.id), codec::arg(1, &value)]).await?;
        Ok(())
    }

    /// Whether the object is visible.
    pub async fn set_visible(&self, value: bool) -> crate::Result<()> {
        self.client.invoke("Drawing", "Line_set_Visible", &[codec::arg(0, &self.id), codec::arg(1, &value)]).await?;
        Ok(())
    }

    /// Remove the object.
    pub async fn remove(&self) -> crate::Result<()> {
        self.client.invoke("Drawing", "Line_Remove", &[codec::arg(0, &self.id)]).await?;
        Ok(())
    }
}

impl PartialEq for Line {
    fn eq(&self, other: &Self) -> bool {
        self.id == other.id
    }
}

impl Eq for Line {}

impl std::hash::Hash for Line {
    fn hash<H: std::hash::Hasher>(&self, state: &mut H) {
        self.id.hash(state);
    }
}

impl Encode for Line {
    fn encode_krpc(&self) -> Vec<u8> {
        self.id.encode_krpc()
    }
}

impl Decode for Line {
    fn decode_krpc(client: &crate::ClientRef, bytes: &[u8]) -> crate::Result<Self> {
        let id = <u64 as Decode>::decode_krpc(client, bytes)?;
        Ok(Self::new(client.clone(), id))
    }
}

impl Decode for Option<Line> {
    fn decode_krpc(client: &crate::ClientRef, bytes: &[u8]) -> crate::Result<Self> {
        let id = <u64 as Decode>::decode_krpc(client, bytes)?;
        Ok(if id == 0 { None } else { Some(Line::new(client.clone(), id)) })
    }
}

/// A polygon. Created using `Drawing.AddPolygon`.
///
/// A remote object handle for a `Drawing.Polygon` instance.
#[derive(Debug, Clone)]
pub struct Polygon {
    client: crate::ClientRef,
    pub(crate) id: u64,
}

impl Polygon {
    pub(crate) fn new(client: crate::ClientRef, id: u64) -> Self {
        Self { client, id }
    }

    /// The id of the remote object this handle refers to.
    pub fn object_id(&self) -> u64 {
        self.id
    }

    /// Set the color
    pub async fn color(&self) -> crate::Result<(f64, f64, f64)> {
        let data = self.client.invoke("Drawing", "Polygon_get_Color", &[codec::arg(0, &self.id)]).await?;
        Decode::decode_krpc(&self.client, &data)
    }

    /// Material used to render the object. Creates the material from a shader with the given name.
    pub async fn material(&self) -> crate::Result<String> {
        let data = self.client.invoke("Drawing", "Polygon_get_Material", &[codec::arg(0, &self.id)]).await?;
        Decode::decode_krpc(&self.client, &data)
    }

    /// Reference frame for the positions of the object.
    pub async fn reference_frame(&self) -> crate::Result<super::space_center::ReferenceFrame> {
        let data = self.client.invoke("Drawing", "Polygon_get_ReferenceFrame", &[codec::arg(0, &self.id)]).await?;
        Decode::decode_krpc(&self.client, &data)
    }

    /// Set the thickness
    pub async fn thickness(&self) -> crate::Result<f32> {
        let data = self.client.invoke("Drawing", "Polygon_get_Thickness", &[codec::arg(0, &self.id)]).await?;
        Decode::decode_krpc(&self.client, &data)
    }

    /// Vertices for the polygon.
    pub async fn vertices(&self) -> crate::Result<Vec<(f64, f64, f64)>> {
        let data = self.client.invoke("Drawing", "Polygon_get_Vertices", &[codec::arg(0, &self.id)]).await?;
        Decode::decode_krpc(&self.client, &data)
    }

    /// Whether the object is visible.
    pub async fn visible(&self) -> crate::Result<bool> {
        let data = self.client.invoke("Drawing", "Polygon_get_Visible", &[codec::arg(0, &self.id)]).await?;
        Decode::decode_krpc(&self.client, &data)
    }

    /// Set the color
    pub async fn set_color(&self, value: (f64, f64, f64)) -> crate::Result<()> {
        self.client.invoke("Drawing", "Polygon_set_Color", &[codec::arg(0, &self.id), codec::arg(1, &value)]).await?;
        Ok(())
    }

    /// Material used to render the object. Creates the material from a shader with the given name.
    pub async fn set_material(&self, value: &str) -> crate::Result<()> {
        self.client.invoke("Drawing", "Polygon_set_Material", &[codec::arg(0, &self.id), codec::arg(1, &value)]).await?;
        Ok(())
    }

    /// Reference frame for the positions of the object.
    pub async fn set_reference_frame(&self, value: &super::space_center::ReferenceFrame) -> crate::Result<()> {
        self.client.invoke("Drawing", "Polygon_set_ReferenceFrame", &[codec::arg(0, &self.id), codec::arg(1, &value)]).await?;
        Ok(())
    }

    /// Set the thickness
    pub async fn set_thickness(&self, value: f32) -> crate::Result<()> {
        self.client.invoke("Drawing", "Polygon_set_Thickness", &[codec::arg(0, &self.id), codec::arg(1, &value)]).await?;
        Ok(())
    }

    /// Vertices for the polygon.
    pub async fn set_vertices(&self, value: Vec<(f64, f64, f64)>) -> crate::Result<()> {
        self.client.invoke("Drawing", "Polygon_set_Vertices", &[codec::arg(0, &self.id), codec::arg(1, &value)]).await?;
        Ok(())
    }

    /// Whether the object is visible.
    pub async fn set_visible(&self, value: bool) -> crate::Result<()> {
        self.client.invoke("Drawing", "Polygon_set_Visible", &[codec::arg(0, &self.id), codec::arg(1, &value)]).await?;
        Ok(())
    }

    /// Remove the object.
    pub async fn remove(&self) -> crate::Result<()> {
        self.client.invoke("Drawing", "Polygon_Remove", &[codec::arg(0, &self.id)]).await?;
        Ok(())
    }
}

impl PartialEq for Polygon {
    fn eq(&self, other: &Self) -> bool {
        self.id == other.id
    }
}

impl Eq for Polygon {}

impl std::hash::Hash for Polygon {
    fn hash<H: std::hash::Hasher>(&self, state: &mut H) {
        self.id.hash(state);
    }
}

impl Encode for Polygon {
    fn encode_krpc(&self) -> Vec<u8> {
        self.id.encode_krpc()
    }
}

impl Decode for Polygon {
    fn decode_krpc(client: &crate::ClientRef, bytes: &[u8]) -> crate::Result<Self> {
        let id = <u64 as Decode>::decode_krpc(client, bytes)?;
        Ok(Self::new(client.clone(), id))
    }
}

impl Decode for Option<Polygon> {
    fn decode_krpc(client: &crate::ClientRef, bytes: &[u8]) -> crate::Result<Self> {
        let id = <u64 as Decode>::decode_krpc(client, bytes)?;
        Ok(if id == 0 { None } else { Some(Polygon::new(client.clone(), id)) })
    }
}

/// Text. Created using `Drawing.AddText`.
///
/// A remote object handle for a `Drawing.Text` instance.
#[derive(Debug, Clone)]
pub struct Text {
    client: crate::ClientRef,
    pub(crate) id: u64,
}

impl Text {
    pub(crate) fn new(client: crate::ClientRef, id: u64) -> Self {
        Self { client, id }
    }

    /// The id of the remote object this handle refers to.
    pub fn object_id(&self) -> u64 {
        self.id
    }

    /// Alignment.
    pub async fn alignment(&self) -> crate::Result<super::ui::TextAlignment> {
        let data = self.client.invoke("Drawing", "Text_get_Alignment", &[codec::arg(0, &self.id)]).await?;
        Decode::decode_krpc(&self.client, &data)
    }

    /// Anchor.
    pub async fn anchor(&self) -> crate::Result<super::ui::TextAnchor> {
        let data = self.client.invoke("Drawing", "Text_get_Anchor", &[codec::arg(0, &self.id)]).await?;
        Decode::decode_krpc(&self.client, &data)
    }

    /// Character size.
    pub async fn character_size(&self) -> crate::Result<f32> {
        let data = self.client.invoke("Drawing", "Text_get_CharacterSize", &[codec::arg(0, &self.id)]).await?;
        Decode::decode_krpc(&self.client, &data)
    }

    /// Set the color
    pub async fn color(&self) -> crate::Result<(f64, f64, f64)> {
        let data = self.client.invoke("Drawing", "Text_get_Color", &[codec::arg(0, &self.id)]).await?;
        Decode::decode_krpc(&self.client, &data)
    }

    /// The text string
    pub async fn content(&self) -> crate::Result<String> {
        let data = self.client.invoke("Drawing", "Text_get_Content", &[codec::arg(0, &self.id)]).await?;
        Decode::decode_krpc(&self.client, &data)
    }

    /// Name of the font
    pub async fn font(&self) -> crate::Result<String> {
        let data = self.client.invoke("Drawing", "Text_get_Font", &[codec::arg(0, &self.id)]).await?;
        Decode::decode_krpc(&self.client, &data)
    }

    /// Line spacing.
    pub async fn line_spacing(&self) -> crate::Result<f32> {
        let data = self.client.invoke("Drawing", "Text_get_LineSpacing", &[codec::arg(0, &self.id)]).await?;
        Decode::decode_krpc(&self.client, &data)
    }

    /// Material used to render the object. Creates the material from a shader with the given name.
    pub async fn material(&self) -> crate::Result<String> {
        let data = self.client.invoke("Drawing", "Text_get_Material", &[codec::arg(0, &self.id)]).await?;
        Decode::decode_krpc(&self.client, &data)
    }

    /// Position of the text.
    pub async fn position(&self) -> crate::Result<(f64, f64, f64)> {
        let data = self.client.invoke("Drawing", "Text_get_Position", &[codec::arg(0, &self.id)]).await?;
        Decode::decode_krpc(&self.client, &data)
    }

    /// Reference frame for the positions of the object.
    pub async fn reference_frame(&self) -> crate::Result<super::space_center::ReferenceFrame> {
        let data = self.client.invoke("Drawing", "Text_get_ReferenceFrame", &[codec::arg(0, &self.id)]).await?;
        Decode::decode_krpc(&self.client, &data)
    }

    /// Rotation of the text as a quaternion.
    pub async fn rotation(&self) -> crate::Result<(f64, f64, f64, f64)> {
        let data = self.client.invoke("Drawing", "Text_get_Rotation", &[codec::arg(0, &self.id)]).await?;
        Decode::decode_krpc(&self.client, &data)
    }

    /// Font size.
    pub async fn size(&self) -> crate::Result<i32> {
        let data = self.client.invoke("Drawing", "Text_get_Size", &[codec::arg(0, &self.id)]).await?;
        Decode::decode_krpc(&self.client, &data)
    }

    /// Font style.
    pub async fn style(&self) -> crate::Result<super::ui::FontStyle> {
        let data = self.client.invoke("Drawing", "Text_get_Style", &[codec::arg(0, &self.id)]).await?;
        Decode::decode_krpc(&self.client, &data)
    }

    /// Whether the object is visible.
    pub async fn visible(&self) -> crate::Result<bool> {
        let data = self.client.invoke("Drawing", "Text_get_Visible", &[codec::arg(0, &self.id)]).await?;
        Decode::decode_krpc(&self.client, &data)
    }

    /// Alignment.
    pub async fn set_alignment(&self, value: super::ui::TextAlignment) -> crate::Result<()> {
        self.client.invoke("Drawing", "Text_set_Alignment", &[codec::arg(0, &self.id), codec::arg(1, &value)]).await?;
        Ok(())
    }

    /// Anchor.
    pub async fn set_anchor(&self, value: super::ui::TextAnchor) -> crate::Result<()> {
        self.client.invoke("Drawing", "Text_set_Anchor", &[codec::arg(0, &self.id), codec::arg(1, &value)]).await?;
        Ok(())
    }

    /// Character size.
    pub async fn set_character_size(&self, value: f32) -> crate::Result<()> {
        self.client.invoke("Drawing", "Text_set_CharacterSize", &[codec::arg(0, &self.id), codec::arg(1, &value)]).await?;
        Ok(())
    }

    /// Set the color
    pub async fn set_color(&self, value: (f64, f64, f64)) -> crate::Result<()> {
        self.client.invoke("Drawing", "Text_set_Color", &[codec::arg(0, &self.id), codec::arg(1, &value)]).await?;
        Ok(())
    }

    /// The text string
    pub async fn set_content(&self, value: &str) -> crate::Result<()> {
        self.client.invoke("Drawing", "Text_set_Content", &[codec::arg(0, &self.id), codec::arg(1, &value)]).await?;
        Ok(())
    }

    /// Name of the font
    pub async fn set_font(&self, value: &str) -> crate::Result<()> {
        self.client.invoke("Drawing", "Text_set_Font", &[codec::arg(0, &self.id), codec::arg(1, &value)]).await?;
        Ok(())
    }

    /// Line spacing.
    pub async fn set_line_spacing(&self, value: f32) -> crate::Result<()> {
        self.client.invoke("Drawing", "Text_set_LineSpacing", &[codec::arg(0, &self.id), codec::arg(1, &value)]).await?;
        Ok(())
    }

    /// Material used to render the object. Creates the material from a shader with the given name.
    pub async fn set_material(&self, value: &str) -> crate::Result<()> {
        self.client.invoke("Drawing", "Text_set_Material", &[codec::arg(0, &self.id), codec::arg(1, &value)]).await?;
        Ok(())
    }

    /// Position of the text.
    pub async fn set_position(&self, value: (f64, f64, f64)) -> crate::Result<()> {
        self.client.invoke("Drawing", "Text_set_Position", &[codec::arg(0, &self.id), codec::arg(1, &value)]).await?;
        Ok(())
    }

    /// Reference frame for the positions of the object.
    pub async fn set_reference_frame(&self, value: &super::space_center::ReferenceFrame) -> crate::Result<()> {
        self.client.invoke("Drawing", "Text_set_ReferenceFrame", &[codec::arg(0, &self.id), codec::arg(1, &value)]).await?;
        Ok(())
    }

    /// Rotation of the text as a quaternion.
    pub async fn set_rotation(&self, value: (f64, f64, f64, f64)) -> crate::Result<()> {
        self.client.invoke("Drawing", "Text_set_Rotation", &[codec::arg(0, &self.id), codec::arg(1, &value)]).await?;
        Ok(())
    }

    /// Font size.
    pub async fn set_size(&self, value: i32) -> crate::Result<()> {
        self.client.invoke("Drawing", "Text_set_Size", &[codec::arg(0, &self.id), codec::arg(1, &value)]).await?;
        Ok(())
    }

    /// Font style.
    pub async fn set_style(&self, value: super::ui::FontStyle) -> crate::Result<()> {
        self.client.invoke("Drawing", "Text_set_Style", &[codec::arg(0, &self.id), codec::arg(1, &value)]).await?;
        Ok(())
    }

    /// Whether the object is visible.
    pub async fn set_visible(&self, value: bool) -> crate::Result<()> {
        self.client.invoke("Drawing", "Text_set_Visible", &[codec::arg(0, &self.id), codec::arg(1, &value)]).await?;
        Ok(())
    }

    /// Remove the object.
    pub async fn remove(&self) -> crate::Result<()> {
        self.client.invoke("Drawing", "Text_Remove", &[codec::arg(0, &self.id)]).await?;
        Ok(())
    }

    /// A list of all available fonts.
    pub async fn available_fonts(client: &crate::ClientRef) -> crate::Result<Vec<String>> {
        let data = client.invoke("Drawing", "Text_static_AvailableFonts", &[]).await?;
        Decode::decode_krpc(client, &data)
    }
}

impl PartialEq for Text {
    fn eq(&self, other: &Self) -> bool {
        self.id == other.id
    }
}

impl Eq for Text {}

impl std::hash::Hash for Text {
    fn hash<H: std::hash::Hasher>(&self, state: &mut H) {
        self.id.hash(state);
    }
}

impl Encode for Text {
    fn encode_krpc(&self) -> Vec<u8> {
        self.id.encode_krpc()
    }
}

impl Decode for Text {
    fn decode_krpc(client: &crate::ClientRef, bytes: &[u8]) -> crate::Result<Self> {
        let id = <u64 as Decode>::decode_krpc(client, bytes)?;
        Ok(Self::new(client.clone(), id))
    }
}

impl Decode for Option<Text> {
    fn decode_krpc(client: &crate::ClientRef, bytes: &[u8]) -> crate::Result<Self> {
        let id = <u64 as Decode>::decode_krpc(client, bytes)?;
        Ok(if id == 0 { None } else { Some(Text::new(client.clone(), id)) })
    }
}

/// Provides functionality for drawing objects in the flight scene.
///
/// For drawing and interacting with the user interface, see the UI service.
pub struct Drawing {
    client: crate::ClientRef,
}

impl Drawing {
    pub fn new(client: crate::ClientRef) -> Self {
        Self { client }
    }

    /// Draw a line in the scene.
    ///
    /// # Arguments
    ///
    /// * `start` - Position of the start of the line.
    /// * `end` - Position of the end of the line.
    /// * `reference_frame` - Reference frame that the positions are in.
    /// * `visible` - Whether the line is visible.
    pub async fn add_line(&self, start: (f64, f64, f64), end: (f64, f64, f64), reference_frame: &super::space_center::ReferenceFrame, visible: Option<bool>) -> crate::Result<Line> {
        let mut args = vec![codec::arg(0, &start), codec::arg(1, &end), codec::arg(2, &reference_frame)];
        if let Some(v) = &visible {
            args.push(codec::arg(3, v));
        }
        let data = self.client.invoke("Drawing", "AddLine", &args).await?;
        Decode::decode_krpc(&self.client, &data)
    }

    /// Draw a direction vector in the scene, starting from the origin of the given reference frame.
    ///
    /// # Arguments
    ///
    /// * `direction` - Direction to draw the line in.
    /// * `reference_frame` - Reference frame that the direction is in and defines the start position.
    /// * `length` - The length of the line.
    /// * `visible` - Whether the line is visible.
    pub async fn add_direction(&self, direction: (f64, f64, f64), reference_frame: &super::space_center::ReferenceFrame, length: Option<f32>, visible: Option<bool>) -> crate::Result<Line> {
        let mut args = vec![codec::arg(0, &direction), codec::arg(1, &reference_frame)];
        if let Some(v) = &length {
            args.push(codec::arg(2, v));
        }
        if let Some(v) = &visible {
            args.push(codec::arg(3, v));
        }
        let data = self.client.invoke("Drawing", "AddDirection", &args).await?;
        Decode::decode_krpc(&self.client, &data)
    }

    /// Draw a direction vector in the scene, from the center of mass of the active vessel.
    ///
    /// # Arguments
    ///
    /// * `direction` - Direction to draw the line in.
    /// * `reference_frame` - Reference frame that the direction is in.
    /// * `length` - The length of the line.
    /// * `visible` - Whether the line is visible.
    pub async fn add_direction_from_com(&self, direction: (f64, f64, f64), reference_frame: &super::space_center::ReferenceFrame, length: Option<f32>, visible: Option<bool>) -> crate::Result<Line> {
        let mut args = vec![codec::arg(0, &direction), codec::arg(1, &reference_frame)];
        if let Some(v) = &length {
            args.push(codec::arg(2, v));
        }
        if let Some(v) = &visible {
            args.push(codec::arg(3, v));
        }
        let data = self.client.invoke("Drawing", "AddDirectionFromCom", &args).await?;
        Decode::decode_krpc(&self.client, &data)
    }

    /// Draw a polygon in the scene, defined by a list of vertices.
    ///
    /// # Arguments
    ///
    /// * `vertices` - Vertices of the polygon.
    /// * `reference_frame` - Reference frame that the vertices are in.
    /// * `visible` - Whether the polygon is visible.
    pub async fn add_polygon(&self, vertices: Vec<(f64, f64, f64)>, reference_frame: &super::space_center::ReferenceFrame, visible: Option<bool>) -> crate::Result<Polygon> {
        let mut args = vec![codec::arg(0, &vertices), codec::arg(1, &reference_frame)];
        if let Some(v) = &visible {
            args.push(codec::arg(2, v));
        }
        let data = self.client.invoke("Drawing", "AddPolygon", &args).await?;
        Decode::decode_krpc(&self.client, &data)
    }

    /// Draw text in the scene.
    ///
    /// # Arguments
    ///
    /// * `text` - The string to draw.
    /// * `reference_frame` - Reference frame that the text position is in.
    /// * `position` - Position of the text.
    /// * `rotation` - Rotation of the text, as a quaternion.
    /// * `visible` - Whether the text is visible.
    pub async fn add_text(&self, text: &str, reference_frame: &super::space_center::ReferenceFrame, position: (f64, f64, f64), rotation: (f64, f64, f64, f64), visible: Option<bool>) -> crate::Result<Text> {
        let mut args = vec![codec::arg(0, &text), codec::arg(1, &reference_frame), codec::arg(2, &position), codec::arg(3, &rotation)];
        if let Some(v) = &visible {
            args.push(codec::arg(4, v));
        }
        let data = self.client.invoke("Drawing", "AddText", &args).await?;
        Decode::decode_krpc(&self.client, &data)
    }

    /// Remove all objects being drawn.
    ///
    /// # Arguments
    ///
    /// * `client_only` - If true, only remove objects created by the calling client.
    pub async fn clear(&self, client_only: Option<bool>) -> crate::Result<()> {
        let mut args = vec![];
        if let Some(v) = &client_only {
            args.push(codec::arg(0, v));
        }
        self.client.invoke("Drawing", "Clear", &args).await?;
        Ok(())
    }
}
