// Generated by stayputnik-codegen. Do not edit.

use crate::codec::{self, Decode, Encode};

/// Represents a servo. Obtained using `InfernalRobotics.ServoGroup.Servos`, `InfernalRobotics.ServoGroup.ServoWithName` or `InfernalRobotics.ServoWithName`.
///
/// A remote object handle for a `InfernalRobotics.Servo` instance.
#[derive(Debug, Clone)]
pub struct Servo {
    client: crate::ClientRef,
    pub(crate) id: u64,
}

impl Servo {
    pub(crate) fn new(client: crate::ClientRef, id: u64) -> Self {
        Self { client, id }
    }

    /// The id of the remote object this handle refers to.
    pub fn object_id(&self) -> u64 {
        self.id
    }

    /// The current speed multiplier set in the UI.
    pub async fn acceleration(&self) -> crate::Result<f32> {
        let data = self.client.invoke("InfernalRobotics", "Servo_get_Acceleration", &[codec::arg(0, &self.id)]).await?;
        Decode::decode_krpc(&self.client, &data)
    }

    /// The speed multiplier of the servo, specified by the part configuration.
    pub async fn config_speed(&self) -> crate::Result<f32> {
        let data = self.client.invoke("InfernalRobotics", "Servo_get_ConfigSpeed", &[codec::arg(0, &self.id)]).await?;
        Decode::decode_krpc(&self.client, &data)
    }

    /// The current speed at which the servo is moving.
    pub async fn current_speed(&self) -> crate::Result<f32> {
        let data = self.client.invoke("InfernalRobotics", "Servo_get_CurrentSpeed", &[codec::arg(0, &self.id)]).await?;
        Decode::decode_krpc(&self.client, &data)
    }

    /// Whether the servos axis is inverted.
    pub async fn is_axis_inverted(&self) -> crate::Result<bool> {
        let data = self.client.invoke("InfernalRobotics", "Servo_get_IsAxisInverted", &[codec::arg(0, &self.id)]).await?;
        Decode::decode_krpc(&self.client, &data)
    }

    /// Whether the servo is freely moving.
    pub async fn is_free_moving(&self) -> crate::Result<bool> {
        let data = self.client.invoke("InfernalRobotics", "Servo_get_IsFreeMoving", &[codec::arg(0, &self.id)]).await?;
        Decode::decode_krpc(&self.client, &data)
    }

    /// Whether the servo is locked.
    pub async fn is_locked(&self) -> crate::Result<bool> {
        let data = self.client.invoke("InfernalRobotics", "Servo_get_IsLocked", &[codec::arg(0, &self.id)]).await?;
        Decode::decode_krpc(&self.client, &data)
    }

    /// Whether the servo is moving.
    pub async fn is_moving(&self) -> crate::Result<bool> {
        let data = self.client.invoke("InfernalRobotics", "Servo_get_IsMoving", &[codec::arg(0, &self.id)]).await?;
        Decode::decode_krpc(&self.client, &data)
    }

    /// The maximum position of the servo, specified by the part configuration.
    pub async fn max_config_position(&self) -> crate::Result<f32> {
        let data = self.client.invoke("InfernalRobotics", "Servo_get_MaxConfigPosition", &[codec::arg(0, &self.id)]).await?;
        Decode::decode_krpc(&self.client, &data)
    }

    /// The maximum position of the servo, specified by the in-game tweak menu.
    pub async fn max_position(&self) -> crate::Result<f32> {
        let data = self.client.invoke("InfernalRobotics", "Servo_get_MaxPosition", &[codec::arg(0, &self.id)]).await?;
        Decode::decode_krpc(&self.client, &data)
    }

    /// The minimum position of the servo, specified by the part configuration.
    pub async fn min_config_position(&self) -> crate::Result<f32> {
        let data = self.client.invoke("InfernalRobotics", "Servo_get_MinConfigPosition", &[codec::arg(0, &self.id)]).await?;
        Decode::decode_krpc(&self.client, &data)
    }

    /// The minimum position of the servo, specified by the in-game tweak menu.
    pub async fn min_position(&self) -> crate::Result<f32> {
        let data = self.client.invoke("InfernalRobotics", "Servo_get_MinPosition", &[codec::arg(0, &self.id)]).await?;
        Decode::decode_krpc(&self.client, &data)
    }

    /// The name of the servo.
    pub async fn name(&self) -> crate::Result<String> {
        let data = self.client.invoke("InfernalRobotics", "Servo_get_Name", &[codec::arg(0, &self.id)]).await?;
        Decode::decode_krpc(&self.client, &data)
    }

    /// The part containing the servo.
    pub async fn part(&self) -> crate::Result<super::space_center::Part> {
        let data = self.client.invoke("InfernalRobotics", "Servo_get_Part", &[codec::arg(0, &self.id)]).await?;
        Decode::decode_krpc(&self.client, &data)
    }

    /// The position of the servo.
    pub async fn position(&self) -> crate::Result<f32> {
        let data = self.client.invoke("InfernalRobotics", "Servo_get_Position", &[codec::arg(0, &self.id)]).await?;
        Decode::decode_krpc(&self.client, &data)
    }

    /// The speed multiplier of the servo, specified by the in-game tweak menu.
    pub async fn speed(&self) -> crate::Result<f32> {
        let data = self.client.invoke("InfernalRobotics", "Servo_get_Speed", &[codec::arg(0, &self.id)]).await?;
        Decode::decode_krpc(&self.client, &data)
    }

    /// The current speed multiplier set in the UI.
    pub async fn set_acceleration(&self, value: f32) -> crate::Result<()> {
        self.client.invoke("InfernalRobotics", "Servo_set_Acceleration", &[codec::arg(0, &self.id), codec::arg(1, &value)]).await?;
        Ok(())
    }

    /// The current speed at which the servo is moving.
    pub async fn set_current_speed(&self, value: f32) -> crate::Result<()> {
        self.client.invoke("InfernalRobotics", "Servo_set_CurrentSpeed", &[codec::arg(0, &self.id), codec::arg(1, &value)]).await?;
        Ok(())
    }

    /// Whether the servo should be highlighted in-game.
    pub async fn set_highlight(&self, value: bool) -> crate::Result<()> {
        self.client.invoke("InfernalRobotics", "Servo_set_Highlight", &[codec::arg(0, &self.id), codec::arg(1, &value)]).await?;
        Ok(())
    }

    /// Whether the servos axis is inverted.
    pub async fn set_is_axis_inverted(&self, value: bool) -> crate::Result<()> {
        self.client.invoke("InfernalRobotics", "Servo_set_IsAxisInverted", &[codec::arg(0, &self.id), codec::arg(1, &value)]).await?;
        Ok(())
    }

    /// Whether the servo is locked.
    pub async fn set_is_locked(&self, value: bool) -> crate::Result<()> {
        self.client.invoke("InfernalRobotics", "Servo_set_IsLocked", &[codec::arg(0, &self.id), codec::arg(1, &value)]).await?;
        Ok(())
    }

    /// The maximum position of the servo, specified by the in-game tweak menu.
    pub async fn set_max_position(&self, value: f32) -> crate::Result<()> {
        self.client.invoke("InfernalRobotics", "Servo_set_MaxPosition", &[codec::arg(0, &self.id), codec::arg(1, &value)]).await?;
        Ok(())
    }

    /// The minimum position of the servo, specified by the in-game tweak menu.
    pub async fn set_min_position(&self, value: f32) -> crate::Result<()> {
        self.client.invoke("InfernalRobotics", "Servo_set_MinPosition", &[codec::arg(0, &self.id), codec::arg(1, &value)]).await?;
        Ok(())
    }

    /// The name of the servo.
    pub async fn set_name(&self, value: &str) -> crate::Result<()> {
        self.client.invoke("InfernalRobotics", "Servo_set_Name", &[codec::arg(0, &self.id), codec::arg(1, &value)]).await?;
        Ok(())
    }

    /// The speed multiplier of the servo, specified by the in-game tweak menu.
    pub async fn set_speed(&self, value: f32) -> crate::Result<()> {
        self.client.invoke("InfernalRobotics", "Servo_set_Speed", &[codec::arg(0, &self.id), codec::arg(1, &value)]).await?;
        Ok(())
    }

    /// Moves the servo to the right.
    pub async fn move_right(&self) -> crate::Result<()> {
        self.client.invoke("InfernalRobotics", "Servo_MoveRight", &[codec::arg(0, &self.id)]).await?;
        Ok(())
    }

    /// Moves the servo to the left.
    pub async fn move_left(&self) -> crate::Result<()> {
        self.client.invoke("InfernalRobotics", "Servo_MoveLeft", &[codec::arg(0, &self.id)]).await?;
        Ok(())
    }

    /// Moves the servo to the center.
    pub async fn move_center(&self) -> crate::Result<()> {
        self.client.invoke("InfernalRobotics", "Servo_MoveCenter", &[codec::arg(0, &self.id)]).await?;
        Ok(())
    }

    /// Moves the servo to the next preset.
    pub async fn move_next_preset(&self) -> crate::Result<()> {
        self.client.invoke("InfernalRobotics", "Servo_MoveNextPreset", &[codec::arg(0, &self.id)]).await?;
        Ok(())
    }

    /// Moves the servo to the previous preset.
    pub async fn move_prev_preset(&self) -> crate::Result<()> {
        self.client.invoke("InfernalRobotics", "Servo_MovePrevPreset", &[codec::arg(0, &self.id)]).await?;
        Ok(())
    }

    /// Moves the servo to `position` and sets the speed multiplier to `speed`.
    ///
    /// # Arguments
    ///
    /// * `position` - The position to move the servo to.
    /// * `speed` - Speed multiplier for the movement.
    pub async fn move_to(&self, position: f32, speed: f32) -> crate::Result<()> {
        self.client.invoke("InfernalRobotics", "Servo_MoveTo", &[codec::arg(0, &self.id), codec::arg(1, &position), codec::arg(2, &speed)]).await?;
        Ok(())
    }

    /// Stops the servo.
    pub async fn stop(&self) -> crate::Result<()> {
        self.client.invoke("InfernalRobotics", "Servo_Stop", &[codec::arg(0, &self.id)]).await?;
        Ok(())
    }
}

impl PartialEq for Servo {
    fn eq(&self, other: &Self) -> bool {
        self.id == other.id
    }
}

impl Eq for Servo {}

impl std::hash::Hash for Servo {
    fn hash<H: std::hash::Hasher>(&self, state: &mut H) {
        self.id.hash(state);
    }
}

impl Encode for Servo {
    fn encode_krpc(&self) -> Vec<u8> {
        self.id.encode_krpc()
    }
}

impl Decode for Servo {
    fn decode_krpc(client: &crate::ClientRef, bytes: &[u8]) -> crate::Result<Self> {
        let id = <u64 as Decode>::decode_krpc(client, bytes)?;
        Ok(Self::new(client.clone(), id))
    }
}

impl Decode for Option<Servo> {
    fn decode_krpc(client: &crate::ClientRef, bytes: &[u8]) -> crate::Result<Self> {
        let id = <u64 as Decode>::decode_krpc(client, bytes)?;
        Ok(if id == 0 { None } else { Some(Servo::new(client.clone(), id)) })
    }
}

/// A group of servos, obtained by calling `InfernalRobotics.ServoGroups` or `InfernalRobotics.ServoGroupWithName`. Represents the "Servo Groups" in the InfernalRobotics UI.
///
/// A remote object handle for a `InfernalRobotics.ServoGroup` instance.
#[derive(Debug, Clone)]
pub struct ServoGroup {
    client: crate::ClientRef,
    pub(crate) id: u64,
}

impl ServoGroup {
    pub(crate) fn new(client: crate::ClientRef, id: u64) -> Self {
        Self { client, id }
    }

    /// The id of the remote object this handle refers to.
    pub fn object_id(&self) -> u64 {
        self.id
    }

    /// Whether the group is expanded in the InfernalRobotics UI.
    pub async fn expanded(&self) -> crate::Result<bool> {
        let data = self.client.invoke("InfernalRobotics", "ServoGroup_get_Expanded", &[codec::arg(0, &self.id)]).await?;
        Decode::decode_krpc(&self.client, &data)
    }

    /// The key assigned to be the "forward" key for the group.
    pub async fn forward_key(&self) -> crate::Result<String> {
        let data = self.client.invoke("InfernalRobotics", "ServoGroup_get_ForwardKey", &[codec::arg(0, &self.id)]).await?;
        Decode::decode_krpc(&self.client, &data)
    }

    /// The name of the group.
    pub async fn name(&self) -> crate::Result<String> {
        let data = self.client.invoke("InfernalRobotics", "ServoGroup_get_Name", &[codec::arg(0, &self.id)]).await?;
        Decode::decode_krpc(&self.client, &data)
    }

    /// The parts containing the servos in the group.
    pub async fn parts(&self) -> crate::Result<Vec<super::space_center::Part>> {
        let data = self.client.invoke("InfernalRobotics", "ServoGroup_get_Parts", &[codec::arg(0, &self.id)]).await?;
        Decode::decode_krpc(&self.client, &data)
    }

    /// The key assigned to be the "reverse" key for the group.
    pub async fn reverse_key(&self) -> crate::Result<String> {
        let data = self.client.invoke("InfernalRobotics", "ServoGroup_get_ReverseKey", &[codec::arg(0, &self.id)]).await?;
        Decode::decode_krpc(&self.client, &data)
    }

    /// The servos that are in the group.
    pub async fn servos(&self) -> crate::Result<Vec<Servo>> {
        let data = self.client.invoke("InfernalRobotics", "ServoGroup_get_Servos", &[codec::arg(0, &self.id)]).await?;
        Decode::decode_krpc(&self.client, &data)
    }

    /// The speed multiplier for the group.
    pub async fn speed(&self) -> crate::Result<f32> {
        let data = self.client.invoke("InfernalRobotics", "ServoGroup_get_Speed", &[codec::arg(0, &self.id)]).await?;
        Decode::decode_krpc(&self.client, &data)
    }

    /// Whether the group is expanded in the InfernalRobotics UI.
    pub async fn set_expanded(&self, value: bool) -> crate::Result<()> {
        self.client.invoke("InfernalRobotics", "ServoGroup_set_Expanded", &[codec::arg(0, &self.id), codec::arg(1, &value)]).await?;
        Ok(())
    }

    /// The key assigned to be the "forward" key for the group.
    pub async fn set_forward_key(&self, value: &str) -> crate::Result<()> {
        self.client.invoke("InfernalRobotics", "ServoGroup_set_ForwardKey", &[codec::arg(0, &self.id), codec::arg(1, &value)]).await?;
        Ok(())
    }

    /// The name of the group.
    pub async fn set_name(&self, value: &str) -> crate::Result<()> {
        self.client.invoke("InfernalRobotics", "ServoGroup_set_Name", &[codec::arg(0, &self.id), codec::arg(1, &value)]).await?;
        Ok(())
    }

    /// The key assigned to be the "reverse" key for the group.
    pub async fn set_reverse_key(&self, value: &str) -> crate::Result<()> {
        self.client.invoke("InfernalRobotics", "ServoGroup_set_ReverseKey", &[codec::arg(0, &self.id), codec::arg(1, &value)]).await?;
        Ok(())
    }

    /// The speed multiplier for the group.
    pub async fn set_speed(&self, value: f32) -> crate::Result<()> {
        self.client.invoke("InfernalRobotics", "ServoGroup_set_Speed", &[codec::arg(0, &self.id), codec::arg(1, &value)]).await?;
        Ok(())
    }

    /// Returns the servo with the given `name` from this group, or `None` if none exists.
    ///
    /// # Arguments
    ///
    /// * `name` - Name of servo to find.
    pub async fn servo_with_name(&self, name: &str) -> crate::Result<Option<Servo>> {
        let data = self.client.invoke("InfernalRobotics", "ServoGroup_ServoWithName", &[codec::arg(0, &self.id), codec::arg(1, &name)]).await?;
        Decode::decode_krpc(&self.client, &data)
    }

    /// Moves all of the servos in the group to the right.
    pub async fn move_right(&self) -> crate::Result<()> {
        self.client.invoke("InfernalRobotics", "ServoGroup_MoveRight", &[codec::arg(0, &self.id)]).await?;
        Ok(())
    }

    /// Moves all of the servos in the group to the left.
    pub async fn move_left(&self) -> crate::Result<()> {
        self.client.invoke("InfernalRobotics", "ServoGroup_MoveLeft", &[codec::arg(0, &self.id)]).await?;
        Ok(())
    }

    /// Moves all of the servos in the group to the center.
    pub async fn move_center(&self) -> crate::Result<()> {
        self.client.invoke("InfernalRobotics", "ServoGroup_MoveCenter", &[codec::arg(0, &self.id)]).await?;
        Ok(())
    }

    /// Moves all of the servos in the group to the next preset.
    pub async fn move_next_preset(&self) -> crate::Result<()> {
        self.client.invoke("InfernalRobotics", "ServoGroup_MoveNextPreset", &[codec::arg(0, &self.id)]).await?;
        Ok(())
    }

    /// Moves all of the servos in the group to the previous preset.
    pub async fn move_prev_preset(&self) -> crate::Result<()> {
        self.client.invoke("InfernalRobotics", "ServoGroup_MovePrevPreset", &[codec::arg(0, &self.id)]).await?;
        Ok(())
    }

    /// Stops the servos in the group.
    pub async fn stop(&self) -> crate::Result<()> {
        self.client.invoke("InfernalRobotics", "ServoGroup_Stop", &[codec::arg(0, &self.id)]).await?;
        Ok(())
    }
}

impl PartialEq for ServoGroup {
    fn eq(&self, other: &Self) -> bool {
        self.id == other.id
    }
}

impl Eq for ServoGroup {}

impl std::hash::Hash for ServoGroup {
    fn hash<H: std::hash::Hasher>(&self, state: &mut H) {
        self.id.hash(state);
    }
}

impl Encode for ServoGroup {
    fn encode_krpc(&self) -> Vec<u8> {
        self.id.encode_krpc()
    }
}

impl Decode for ServoGroup {
    fn decode_krpc(client: &crate::ClientRef, bytes: &[u8]) -> crate::Result<Self> {
        let id = <u64 as Decode>::decode_krpc(client, bytes)?;
        Ok(Self::new(client.clone(), id))
    }
}

impl Decode for Option<ServoGroup> {
    fn decode_krpc(client: &crate::ClientRef, bytes: &[u8]) -> crate::Result<Self> {
        let id = <u64 as Decode>::decode_krpc(client, bytes)?;
        Ok(if id == 0 { None } else { Some(ServoGroup::new(client.clone(), id)) })
    }
}

/// This service provides functionality to interact with [Infernal Robotics](https://forum.kerbalspaceprogram.com/index.php?/topic/104535-112-magic-smoke-industries-infernal-robotics-202/).
pub struct InfernalRobotics {
    client: crate::ClientRef,
}

impl InfernalRobotics {
    pub fn new(client: crate::ClientRef) -> Self {
        Self { client }
    }

    /// Whether Infernal Robotics is installed.
    pub async fn available(&self) -> crate::Result<bool> {
        let data = self.client.invoke("InfernalRobotics", "get_Available", &[]).await?;
        Decode::decode_krpc(&self.client, &data)
    }

    /// Whether Infernal Robotics API is ready.
    pub async fn ready(&self) -> crate::Result<bool> {
        let data = self.client.invoke("InfernalRobotics", "get_Ready", &[]).await?;
        Decode::decode_krpc(&self.client, &data)
    }

    /// A list of all the servo groups in the given `vessel`.
    pub async fn servo_groups(&self, vessel: &super::space_center::Vessel) -> crate::Result<Vec<ServoGroup>> {
        let data = self.client.invoke("InfernalRobotics", "ServoGroups", &[codec::arg(0, &vessel)]).await?;
        Decode::decode_krpc(&self.client, &data)
    }

    /// Returns the servo group in the given `vessel` with the given `name`, or `None` if none exists. If multiple servo groups have the same name, only one of them is returned.
    ///
    /// # Arguments
    ///
    /// * `vessel` - Vessel to check.
    /// * `name` - Name of servo group to find.
    pub async fn servo_group_with_name(&self, vessel: &super::space_center::Vessel, name: &str) -> crate::Result<Option<ServoGroup>> {
        let data = self.client.invoke("InfernalRobotics", "ServoGroupWithName", &[codec::arg(0, &vessel), codec::arg(1, &name)]).await?;
        Decode::decode_krpc(&self.client, &data)
    }

    /// Returns the servo in the given `vessel` with the given `name` or `None` if none exists. If multiple servos have the same name, only one of them is returned.
    ///
    /// # Arguments
    ///
    /// * `vessel` - Vessel to check.
    /// * `name` - Name of the servo to find.
    pub async fn servo_with_name(&self, vessel: &super::space_center::Vessel, name: &str) -> crate::Result<Option<Servo>> {
        let data = self.client.invoke("InfernalRobotics", "ServoWithName", &[codec::arg(0, &vessel), codec::arg(1, &name)]).await?;
        Decode::decode_krpc(&self.client, &data)
    }
}
