// Generated by stayputnik-codegen. Do not edit.

use crate::codec::{self, Decode, Encode};

/// The game scene. See `KRPC.CurrentGameScene`.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
#[repr(i32)]
pub enum GameScene {
    /// The game scene showing the Kerbal Space Center buildings.
    SpaceCenter = 0,
    /// The game scene showing a vessel in flight (or on the launchpad/runway).
    Flight = 1,
    /// The tracking station.
    TrackingStation = 2,
    /// The Vehicle Assembly Building.
    EditorVab = 3,
    /// The Space Plane Hangar.
    EditorSph = 4,
}

impl TryFrom<i32> for GameScene {
    type Error = crate::Error;

    fn try_from(value: i32) -> Result<Self, Self::Error> {
        match value {
            0 => Ok(Self::SpaceCenter),
            1 => Ok(Self::Flight),
            2 => Ok(Self::TrackingStation),
            3 => Ok(Self::EditorVab),
            4 => Ok(Self::EditorSph),
            _ => Err(crate::Error::Decode(prost::DecodeError::new(format!("unknown enum value {} for GameScene", value)))),
        }
    }
}

impl Encode for GameScene {
    fn encode_krpc(&self) -> Vec<u8> {
        (*self as i32).encode_krpc()
    }
}

impl Decode for GameScene {
    fn decode_krpc(client: &crate::ClientRef, bytes: &[u8]) -> crate::Result<Self> {
        Self::try_from(<i32 as Decode>::decode_krpc(client, bytes)?)
    }
}

/// A server side expression.
///
/// A remote object handle for a `KRPC.Expression` instance.
#[derive(Debug, Clone)]
pub struct Expression {
    #[allow(dead_code)]
    client: crate::ClientRef,
    pub(crate) id: u64,
}

impl Expression {
    pub(crate) fn new(client: crate::ClientRef, id: u64) -> Self {
        Self { client, id }
    }

    /// The id of the remote object this handle refers to.
    pub fn object_id(&self) -> u64 {
        self.id
    }

    /// A constant value of double precision floating point type.
    pub async fn constant_double(client: &crate::ClientRef, value: f64) -> crate::Result<Expression> {
        let data = client.invoke("KRPC", "Expression_static_ConstantDouble", &[codec::arg(0, &value)]).await?;
        Decode::decode_krpc(client, &data)
    }

    /// Streamed variant of `constant_double`: the server pushes the value
    /// at the stream's update rate instead of being polled.
    pub async fn constant_double_stream(client: &crate::ClientRef, value: f64) -> crate::Result<crate::Stream<Expression>> {
        client.stream("KRPC", "Expression_static_ConstantDouble", &[codec::arg(0, &value)]).await
    }

    /// A constant value of single precision floating point type.
    pub async fn constant_float(client: &crate::ClientRef, value: f32) -> crate::Result<Expression> {
        let data = client.invoke("KRPC", "Expression_static_ConstantFloat", &[codec::arg(0, &value)]).await?;
        Decode::decode_krpc(client, &data)
    }

    /// Streamed variant of `constant_float`: the server pushes the value
    /// at the stream's update rate instead of being polled.
    pub async fn constant_float_stream(client: &crate::ClientRef, value: f32) -> crate::Result<crate::Stream<Expression>> {
        client.stream("KRPC", "Expression_static_ConstantFloat", &[codec::arg(0, &value)]).await
    }

    /// A constant value of integer type.
    pub async fn constant_int(client: &crate::ClientRef, value: i32) -> crate::Result<Expression> {
        let data = client.invoke("KRPC", "Expression_static_ConstantInt", &[codec::arg(0, &value)]).await?;
        Decode::decode_krpc(client, &data)
    }

    /// Streamed variant of `constant_int`: the server pushes the value
    /// at the stream's update rate instead of being polled.
    pub async fn constant_int_stream(client: &crate::ClientRef, value: i32) -> crate::Result<crate::Stream<Expression>> {
        client.stream("KRPC", "Expression_static_ConstantInt", &[codec::arg(0, &value)]).await
    }

    /// A constant value of boolean type.
    pub async fn constant_bool(client: &crate::ClientRef, value: bool) -> crate::Result<Expression> {
        let data = client.invoke("KRPC", "Expression_static_ConstantBool", &[codec::arg(0, &value)]).await?;
        Decode::decode_krpc(client, &data)
    }

    /// Streamed variant of `constant_bool`: the server pushes the value
    /// at the stream's update rate instead of being polled.
    pub async fn constant_bool_stream(client: &crate::ClientRef, value: bool) -> crate::Result<crate::Stream<Expression>> {
        client.stream("KRPC", "Expression_static_ConstantBool", &[codec::arg(0, &value)]).await
    }

    /// A constant value of string type.
    pub async fn constant_string(client: &crate::ClientRef, value: &str) -> crate::Result<Expression> {
        let data = client.invoke("KRPC", "Expression_static_ConstantString", &[codec::arg(0, &value)]).await?;
        Decode::decode_krpc(client, &data)
    }

    /// Streamed variant of `constant_string`: the server pushes the value
    /// at the stream's update rate instead of being polled.
    pub async fn constant_string_stream(client: &crate::ClientRef, value: &str) -> crate::Result<crate::Stream<Expression>> {
        client.stream("KRPC", "Expression_static_ConstantString", &[codec::arg(0, &value)]).await
    }

    /// An RPC call.
    pub async fn call(client: &crate::ClientRef, call: &crate::krpc::schema::ProcedureCall) -> crate::Result<Expression> {
        let data = client.invoke("KRPC", "Expression_static_Call", &[codec::arg(0, &call)]).await?;
        Decode::decode_krpc(client, &data)
    }

    /// Streamed variant of `call`: the server pushes the value
    /// at the stream's update rate instead of being polled.
    pub async fn call_stream(client: &crate::ClientRef, call: &crate::krpc::schema::ProcedureCall) -> crate::Result<crate::Stream<Expression>> {
        client.stream("KRPC", "Expression_static_Call", &[codec::arg(0, &call)]).await
    }

    /// Equality comparison.
    pub async fn equal(client: &crate::ClientRef, arg0: &Expression, arg1: &Expression) -> crate::Result<Expression> {
        let data = client.invoke("KRPC", "Expression_static_Equal", &[codec::arg(0, &arg0), codec::arg(1, &arg1)]).await?;
        Decode::decode_krpc(client, &data)
    }

    /// Streamed variant of `equal`: the server pushes the value
    /// at the stream's update rate instead of being polled.
    pub async fn equal_stream(client: &crate::ClientRef, arg0: &Expression, arg1: &Expression) -> crate::Result<crate::Stream<Expression>> {
        client.stream("KRPC", "Expression_static_Equal", &[codec::arg(0, &arg0), codec::arg(1, &arg1)]).await
    }

    /// Inequality comparison.
    pub async fn not_equal(client: &crate::ClientRef, arg0: &Expression, arg1: &Expression) -> crate::Result<Expression> {
        let data = client.invoke("KRPC", "Expression_static_NotEqual", &[codec::arg(0, &arg0), codec::arg(1, &arg1)]).await?;
        Decode::decode_krpc(client, &data)
    }

    /// Streamed variant of `not_equal`: the server pushes the value
    /// at the stream's update rate instead of being polled.
    pub async fn not_equal_stream(client: &crate::ClientRef, arg0: &Expression, arg1: &Expression) -> crate::Result<crate::Stream<Expression>> {
        client.stream("KRPC", "Expression_static_NotEqual", &[codec::arg(0, &arg0), codec::arg(1, &arg1)]).await
    }

    /// Greater than numerical comparison.
    pub async fn greater_than(client: &crate::ClientRef, arg0: &Expression, arg1: &Expression) -> crate::Result<Expression> {
        let data = client.invoke("KRPC", "Expression_static_GreaterThan", &[codec::arg(0, &arg0), codec::arg(1, &arg1)]).await?;
        Decode::decode_krpc(client, &data)
    }

    /// Streamed variant of `greater_than`: the server pushes the value
    /// at the stream's update rate instead of being polled.
    pub async fn greater_than_stream(client: &crate::ClientRef, arg0: &Expression, arg1: &Expression) -> crate::Result<crate::Stream<Expression>> {
        client.stream("KRPC", "Expression_static_GreaterThan", &[codec::arg(0, &arg0), codec::arg(1, &arg1)]).await
    }

    /// Greater than or equal numerical comparison.
    pub async fn greater_than_or_equal(client: &crate::ClientRef, arg0: &Expression, arg1: &Expression) -> crate::Result<Expression> {
        let data = client.invoke("KRPC", "Expression_static_GreaterThanOrEqual", &[codec::arg(0, &arg0), codec::arg(1, &arg1)]).await?;
        Decode::decode_krpc(client, &data)
    }

    /// Streamed variant of `greater_than_or_equal`: the server pushes the value
    /// at the stream's update rate instead of being polled.
    pub async fn greater_than_or_equal_stream(client: &crate::ClientRef, arg0: &Expression, arg1: &Expression) -> crate::Result<crate::Stream<Expression>> {
        client.stream("KRPC", "Expression_static_GreaterThanOrEqual", &[codec::arg(0, &arg0), codec::arg(1, &arg1)]).await
    }

    /// Less than numerical comparison.
    pub async fn less_than(client: &crate::ClientRef, arg0: &Expression, arg1: &Expression) -> crate::Result<Expression> {
        let data = client.invoke("KRPC", "Expression_static_LessThan", &[codec::arg(0, &arg0), codec::arg(1, &arg1)]).await?;
        Decode::decode_krpc(client, &data)
    }

    /// Streamed variant of `less_than`: the server pushes the value
    /// at the stream's update rate instead of being polled.
    pub async fn less_than_stream(client: &crate::ClientRef, arg0: &Expression, arg1: &Expression) -> crate::Result<crate::Stream<Expression>> {
        client.stream("KRPC", "Expression_static_LessThan", &[codec::arg(0, &arg0), codec::arg(1, &arg1)]).await
    }

    /// Less than or equal numerical comparison.
    pub async fn less_than_or_equal(client: &crate::ClientRef, arg0: &Expression, arg1: &Expression) -> crate::Result<Expression> {
        let data = client.invoke("KRPC", "Expression_static_LessThanOrEqual", &[codec::arg(0, &arg0), codec::arg(1, &arg1)]).await?;
        Decode::decode_krpc(client, &data)
    }

    /// Streamed variant of `less_than_or_equal`: the server pushes the value
    /// at the stream's update rate instead of being polled.
    pub async fn less_than_or_equal_stream(client: &crate::ClientRef, arg0: &Expression, arg1: &Expression) -> crate::Result<crate::Stream<Expression>> {
        client.stream("KRPC", "Expression_static_LessThanOrEqual", &[codec::arg(0, &arg0), codec::arg(1, &arg1)]).await
    }

    /// Boolean and operator.
    pub async fn and(client: &crate::ClientRef, arg0: &Expression, arg1: &Expression) -> crate::Result<Expression> {
        let data = client.invoke("KRPC", "Expression_static_And", &[codec::arg(0, &arg0), codec::arg(1, &arg1)]).await?;
        Decode::decode_krpc(client, &data)
    }

    /// Streamed variant of `and`: the server pushes the value
    /// at the stream's update rate instead of being polled.
    pub async fn and_stream(client: &crate::ClientRef, arg0: &Expression, arg1: &Expression) -> crate::Result<crate::Stream<Expression>> {
        client.stream("KRPC", "Expression_static_And", &[codec::arg(0, &arg0), codec::arg(1, &arg1)]).await
    }

    /// Boolean or operator.
    pub async fn or(client: &crate::ClientRef, arg0: &Expression, arg1: &Expression) -> crate::Result<Expression> {
        let data = client.invoke("KRPC", "Expression_static_Or", &[codec::arg(0, &arg0), codec::arg(1, &arg1)]).await?;
        Decode::decode_krpc(client, &data)
    }

    /// Streamed variant of `or`: the server pushes the value
    /// at the stream's update rate instead of being polled.
    pub async fn or_stream(client: &crate::ClientRef, arg0: &Expression, arg1: &Expression) -> crate::Result<crate::Stream<Expression>> {
        client.stream("KRPC", "Expression_static_Or", &[codec::arg(0, &arg0), codec::arg(1, &arg1)]).await
    }

    /// Boolean exclusive-or operator.
    pub async fn exclusive_or(client: &crate::ClientRef, arg0: &Expression, arg1: &Expression) -> crate::Result<Expression> {
        let data = client.invoke("KRPC", "Expression_static_ExclusiveOr", &[codec::arg(0, &arg0), codec::arg(1, &arg1)]).await?;
        Decode::decode_krpc(client, &data)
    }

    /// Streamed variant of `exclusive_or`: the server pushes the value
    /// at the stream's update rate instead of being polled.
    pub async fn exclusive_or_stream(client: &crate::ClientRef, arg0: &Expression, arg1: &Expression) -> crate::Result<crate::Stream<Expression>> {
        client.stream("KRPC", "Expression_static_ExclusiveOr", &[codec::arg(0, &arg0), codec::arg(1, &arg1)]).await
    }

    /// Boolean negation operator.
    pub async fn not(client: &crate::ClientRef, arg: &Expression) -> crate::Result<Expression> {
        let data = client.invoke("KRPC", "Expression_static_Not", &[codec::arg(0, &arg)]).await?;
        Decode::decode_krpc(client, &data)
    }

    /// Streamed variant of `not`: the server pushes the value
    /// at the stream's update rate instead of being polled.
    pub async fn not_stream(client: &crate::ClientRef, arg: &Expression) -> crate::Result<crate::Stream<Expression>> {
        client.stream("KRPC", "Expression_static_Not", &[codec::arg(0, &arg)]).await
    }

    /// Numerical addition.
    pub async fn add(client: &crate::ClientRef, arg0: &Expression, arg1: &Expression) -> crate::Result<Expression> {
        let data = client.invoke("KRPC", "Expression_static_Add", &[codec::arg(0, &arg0), codec::arg(1, &arg1)]).await?;
        Decode::decode_krpc(client, &data)
    }

    /// Streamed variant of `add`: the server pushes the value
    /// at the stream's update rate instead of being polled.
    pub async fn add_stream(client: &crate::ClientRef, arg0: &Expression, arg1: &Expression) -> crate::Result<crate::Stream<Expression>> {
        client.stream("KRPC", "Expression_static_Add", &[codec::arg(0, &arg0), codec::arg(1, &arg1)]).await
    }

    /// Numerical subtraction.
    pub async fn subtract(client: &crate::ClientRef, arg0: &Expression, arg1: &Expression) -> crate::Result<Expression> {
        let data = client.invoke("KRPC", "Expression_static_Subtract", &[codec::arg(0, &arg0), codec::arg(1, &arg1)]).await?;
        Decode::decode_krpc(client, &data)
    }

    /// Streamed variant of `subtract`: the server pushes the value
    /// at the stream's update rate instead of being polled.
    pub async fn subtract_stream(client: &crate::ClientRef, arg0: &Expression, arg1: &Expression) -> crate::Result<crate::Stream<Expression>> {
        client.stream("KRPC", "Expression_static_Subtract", &[codec::arg(0, &arg0), codec::arg(1, &arg1)]).await
    }

    /// Numerical multiplication.
    pub async fn multiply(client: &crate::ClientRef, arg0: &Expression, arg1: &Expression) -> crate::Result<Expression> {
        let data = client.invoke("KRPC", "Expression_static_Multiply", &[codec::arg(0, &arg0), codec::arg(1, &arg1)]).await?;
        Decode::decode_krpc(client, &data)
    }

    /// Streamed variant of `multiply`: the server pushes the value
    /// at the stream's update rate instead of being polled.
    pub async fn multiply_stream(client: &crate::ClientRef, arg0: &Expression, arg1: &Expression) -> crate::Result<crate::Stream<Expression>> {
        client.stream("KRPC", "Expression_static_Multiply", &[codec::arg(0, &arg0), codec::arg(1, &arg1)]).await
    }

    /// Numerical division.
    pub async fn divide(client: &crate::ClientRef, arg0: &Expression, arg1: &Expression) -> crate::Result<Expression> {
        let data = client.invoke("KRPC", "Expression_static_Divide", &[codec::arg(0, &arg0), codec::arg(1, &arg1)]).await?;
        Decode::decode_krpc(client, &data)
    }

    /// Streamed variant of `divide`: the server pushes the value
    /// at the stream's update rate instead of being polled.
    pub async fn divide_stream(client: &crate::ClientRef, arg0: &Expression, arg1: &Expression) -> crate::Result<crate::Stream<Expression>> {
        client.stream("KRPC", "Expression_static_Divide", &[codec::arg(0, &arg0), codec::arg(1, &arg1)]).await
    }

    /// Numerical modulo operator.
    ///
    /// # Returns
    ///
    /// The remainder of arg0 divided by arg1
    pub async fn modulo(client: &crate::ClientRef, arg0: &Expression, arg1: &Expression) -> crate::Result<Expression> {
        let data = client.invoke("KRPC", "Expression_static_Modulo", &[codec::arg(0, &arg0), codec::arg(1, &arg1)]).await?;
        Decode::decode_krpc(client, &data)
    }

    /// Streamed variant of `modulo`: the server pushes the value
    /// at the stream's update rate instead of being polled.
    pub async fn modulo_stream(client: &crate::ClientRef, arg0: &Expression, arg1: &Expression) -> crate::Result<crate::Stream<Expression>> {
        client.stream("KRPC", "Expression_static_Modulo", &[codec::arg(0, &arg0), codec::arg(1, &arg1)]).await
    }

    /// Numerical power operator.
    ///
    /// # Returns
    ///
    /// arg0 raised to the power of arg1, with type of arg0
    pub async fn power(client: &crate::ClientRef, arg0: &Expression, arg1: &Expression) -> crate::Result<Expression> {
        let data = client.invoke("KRPC", "Expression_static_Power", &[codec::arg(0, &arg0), codec::arg(1, &arg1)]).await?;
        Decode::decode_krpc(client, &data)
    }

    /// Streamed variant of `power`: the server pushes the value
    /// at the stream's update rate instead of being polled.
    pub async fn power_stream(client: &crate::ClientRef, arg0: &Expression, arg1: &Expression) -> crate::Result<crate::Stream<Expression>> {
        client.stream("KRPC", "Expression_static_Power", &[codec::arg(0, &arg0), codec::arg(1, &arg1)]).await
    }

    /// Bitwise left shift.
    pub async fn left_shift(client: &crate::ClientRef, arg0: &Expression, arg1: &Expression) -> crate::Result<Expression> {
        let data = client.invoke("KRPC", "Expression_static_LeftShift", &[codec::arg(0, &arg0), codec::arg(1, &arg1)]).await?;
        Decode::decode_krpc(client, &data)
    }

    /// Streamed variant of `left_shift`: the server pushes the value
    /// at the stream's update rate instead of being polled.
    pub async fn left_shift_stream(client: &crate::ClientRef, arg0: &Expression, arg1: &Expression) -> crate::Result<crate::Stream<Expression>> {
        client.stream("KRPC", "Expression_static_LeftShift", &[codec::arg(0, &arg0), codec::arg(1, &arg1)]).await
    }

    /// Bitwise right shift.
    pub async fn right_shift(client: &crate::ClientRef, arg0: &Expression, arg1: &Expression) -> crate::Result<Expression> {
        let data = client.invoke("KRPC", "Expression_static_RightShift", &[codec::arg(0, &arg0), codec::arg(1, &arg1)]).await?;
        Decode::decode_krpc(client, &data)
    }

    /// Streamed variant of `right_shift`: the server pushes the value
    /// at the stream's update rate instead of being polled.
    pub async fn right_shift_stream(client: &crate::ClientRef, arg0: &Expression, arg1: &Expression) -> crate::Result<crate::Stream<Expression>> {
        client.stream("KRPC", "Expression_static_RightShift", &[codec::arg(0, &arg0), codec::arg(1, &arg1)]).await
    }

    /// Perform a cast to the given type.
    ///
    /// # Arguments
    ///
    /// * `r#type` - Type to cast the argument to.
    pub async fn cast(client: &crate::ClientRef, arg: &Expression, r#type: &Type) -> crate::Result<Expression> {
        let data = client.invoke("KRPC", "Expression_static_Cast", &[codec::arg(0, &arg), codec::arg(1, &r#type)]).await?;
        Decode::decode_krpc(client, &data)
    }

    /// Streamed variant of `cast`: the server pushes the value
    /// at the stream's update rate instead of being polled.
    pub async fn cast_stream(client: &crate::ClientRef, arg: &Expression, r#type: &Type) -> crate::Result<crate::Stream<Expression>> {
        client.stream("KRPC", "Expression_static_Cast", &[codec::arg(0, &arg), codec::arg(1, &r#type)]).await
    }

    /// A named parameter of type double.
    ///
    /// # Arguments
    ///
    /// * `name` - The name of the parameter.
    /// * `r#type` - The type of the parameter.
    ///
    /// # Returns
    ///
    /// A named parameter.
    pub async fn parameter(client: &crate::ClientRef, name: &str, r#type: &Type) -> crate::Result<Expression> {
        let data = client.invoke("KRPC", "Expression_static_Parameter", &[codec::arg(0, &name), codec::arg(1, &r#type)]).await?;
        Decode::decode_krpc(client, &data)
    }

    /// Streamed variant of `parameter`: the server pushes the value
    /// at the stream's update rate instead of being polled.
    pub async fn parameter_stream(client: &crate::ClientRef, name: &str, r#type: &Type) -> crate::Result<crate::Stream<Expression>> {
        client.stream("KRPC", "Expression_static_Parameter", &[codec::arg(0, &name), codec::arg(1, &r#type)]).await
    }

    /// A function.
    ///
    /// # Arguments
    ///
    /// * `parameters` - The parameters of the function.
    /// * `body` - The body of the function.
    ///
    /// # Returns
    ///
    /// A function.
    pub async fn function(client: &crate::ClientRef, parameters: Vec<Expression>, body: &Expression) -> crate::Result<Expression> {
        let data = client.invoke("KRPC", "Expression_static_Function", &[codec::arg(0, &parameters), codec::arg(1, &body)]).await?;
        Decode::decode_krpc(client, &data)
    }

    /// Streamed variant of `function`: the server pushes the value
    /// at the stream's update rate instead of being polled.
    pub async fn function_stream(client: &crate::ClientRef, parameters: Vec<Expression>, body: &Expression) -> crate::Result<crate::Stream<Expression>> {
        client.stream("KRPC", "Expression_static_Function", &[codec::arg(0, &parameters), codec::arg(1, &body)]).await
    }

    /// A function call.
    ///
    /// # Arguments
    ///
    /// * `function` - The function to call.
    /// * `args` - The arguments to call the function with.
    ///
    /// # Returns
    ///
    /// A function call.
    pub async fn invoke(client: &crate::ClientRef, function: &Expression, args: std::collections::HashMap<String, Expression>) -> crate::Result<Expression> {
        let data = client.invoke("KRPC", "Expression_static_Invoke", &[codec::arg(0, &function), codec::arg(1, &args)]).await?;
        Decode::decode_krpc(client, &data)
    }

    /// Streamed variant of `invoke`: the server pushes the value
    /// at the stream's update rate instead of being polled.
    pub async fn invoke_stream(client: &crate::ClientRef, function: &Expression, args: std::collections::HashMap<String, Expression>) -> crate::Result<crate::Stream<Expression>> {
        client.stream("KRPC", "Expression_static_Invoke", &[codec::arg(0, &function), codec::arg(1, &args)]).await
    }

    /// Construct a tuple.
    ///
    /// # Arguments
    ///
    /// * `elements` - The elements.
    ///
    /// # Returns
    ///
    /// The tuple.
    pub async fn create_tuple(client: &crate::ClientRef, elements: Vec<Expression>) -> crate::Result<Expression> {
        let data = client.invoke("KRPC", "Expression_static_CreateTuple", &[codec::arg(0, &elements)]).await?;
        Decode::decode_krpc(client, &data)
    }

    /// Streamed variant of `create_tuple`: the server pushes the value
    /// at the stream's update rate instead of being polled.
    pub async fn create_tuple_stream(client: &crate::ClientRef, elements: Vec<Expression>) -> crate::Result<crate::Stream<Expression>> {
        client.stream("KRPC", "Expression_static_CreateTuple", &[codec::arg(0, &elements)]).await
    }

    /// Construct a list.
    ///
    /// # Arguments
    ///
    /// * `values` - The value. Should all be of the same type.
    ///
    /// # Returns
    ///
    /// The list.
    pub async fn create_list(client: &crate::ClientRef, values: Vec<Expression>) -> crate::Result<Expression> {
        let data = client.invoke("KRPC", "Expression_static_CreateList", &[codec::arg(0, &values)]).await?;
        Decode::decode_krpc(client, &data)
    }

    /// Streamed variant of `create_list`: the server pushes the value
    /// at the stream's update rate instead of being polled.
    pub async fn create_list_stream(client: &crate::ClientRef, values: Vec<Expression>) -> crate::Result<crate::Stream<Expression>> {
        client.stream("KRPC", "Expression_static_CreateList", &[codec::arg(0, &values)]).await
    }

    /// Construct a set.
    ///
    /// # Arguments
    ///
    /// * `values` - The values. Should all be of the same type.
    ///
    /// # Returns
    ///
    /// The set.
    pub async fn create_set(client: &crate::ClientRef, values: std::collections::HashSet<Expression>) -> crate::Result<Expression> {
        let data = client.invoke("KRPC", "Expression_static_CreateSet", &[codec::arg(0, &values)]).await?;
        Decode::decode_krpc(client, &data)
    }

    /// Streamed variant of `create_set`: the server pushes the value
    /// at the stream's update rate instead of being polled.
    pub async fn create_set_stream(client: &crate::ClientRef, values: std::collections::HashSet<Expression>) -> crate::Result<crate::Stream<Expression>> {
        client.stream("KRPC", "Expression_static_CreateSet", &[codec::arg(0, &values)]).await
    }

    /// Construct a dictionary, from a list of corresponding keys and values.
    ///
    /// # Arguments
    ///
    /// * `keys` - The keys. Should all be of the same type.
    /// * `values` - The values. Should all be of the same type.
    ///
    /// # Returns
    ///
    /// The dictionary.
    pub async fn create_dictionary(client: &crate::ClientRef, keys: Vec<Expression>, values: Vec<Expression>) -> crate::Result<Expression> {
        let data = client.invoke("KRPC", "Expression_static_CreateDictionary", &[codec::arg(0, &keys), codec::arg(1, &values)]).await?;
        Decode::decode_krpc(client, &data)
    }

    /// Streamed variant of `create_dictionary`: the server pushes the value
    /// at the stream's update rate instead of being polled.
    pub async fn create_dictionary_stream(client: &crate::ClientRef, keys: Vec<Expression>, values: Vec<Expression>) -> crate::Result<crate::Stream<Expression>> {
        client.stream("KRPC", "Expression_static_CreateDictionary", &[codec::arg(0, &keys), codec::arg(1, &values)]).await
    }

    /// Convert a collection to a list.
    ///
    /// # Arguments
    ///
    /// * `arg` - The collection.
    ///
    /// # Returns
    ///
    /// The collection as a list.
    pub async fn to_list(client: &crate::ClientRef, arg: &Expression) -> crate::Result<Expression> {
        let data = client.invoke("KRPC", "Expression_static_ToList", &[codec::arg(0, &arg)]).await?;
        Decode::decode_krpc(client, &data)
    }

    /// Streamed variant of `to_list`: the server pushes the value
    /// at the stream's update rate instead of being polled.
    pub async fn to_list_stream(client: &crate::ClientRef, arg: &Expression) -> crate::Result<crate::Stream<Expression>> {
        client.stream("KRPC", "Expression_static_ToList", &[codec::arg(0, &arg)]).await
    }

    /// Convert a collection to a set.
    ///
    /// # Arguments
    ///
    /// * `arg` - The collection.
    ///
    /// # Returns
    ///
    /// The collection as a set.
    pub async fn to_set(client: &crate::ClientRef, arg: &Expression) -> crate::Result<Expression> {
        let data = client.invoke("KRPC", "Expression_static_ToSet", &[codec::arg(0, &arg)]).await?;
        Decode::decode_krpc(client, &data)
    }

    /// Streamed variant of `to_set`: the server pushes the value
    /// at the stream's update rate instead of being polled.
    pub async fn to_set_stream(client: &crate::ClientRef, arg: &Expression) -> crate::Result<crate::Stream<Expression>> {
        client.stream("KRPC", "Expression_static_ToSet", &[codec::arg(0, &arg)]).await
    }

    /// Access an element in a tuple, list or dictionary.
    ///
    /// # Arguments
    ///
    /// * `arg` - The tuple, list or dictionary.
    /// * `index` - The index of the element to access. A zero indexed integer for a tuple or list, or a key for a dictionary.
    ///
    /// # Returns
    ///
    /// The element.
    pub async fn get(client: &crate::ClientRef, arg: &Expression, index: &Expression) -> crate::Result<Expression> {
        let data = client.invoke("KRPC", "Expression_static_Get", &[codec::arg(0, &arg), codec::arg(1, &index)]).await?;
        Decode::decode_krpc(client, &data)
    }

    /// Streamed variant of `get`: the server pushes the value
    /// at the stream's update rate instead of being polled.
    pub async fn get_stream(client: &crate::ClientRef, arg: &Expression, index: &Expression) -> crate::Result<crate::Stream<Expression>> {
        client.stream("KRPC", "Expression_static_Get", &[codec::arg(0, &arg), codec::arg(1, &index)]).await
    }

    /// Number of elements in a collection.
    ///
    /// # Arguments
    ///
    /// * `arg` - The list, set or dictionary.
    ///
    /// # Returns
    ///
    /// The number of elements in the collection.
    pub async fn count(client: &crate::ClientRef, arg: &Expression) -> crate::Result<Expression> {
        let data = client.invoke("KRPC", "Expression_static_Count", &[codec::arg(0, &arg)]).await?;
        Decode::decode_krpc(client, &data)
    }

    /// Streamed variant of `count`: the server pushes the value
    /// at the stream's update rate instead of being polled.
    pub async fn count_stream(client: &crate::ClientRef, arg: &Expression) -> crate::Result<crate::Stream<Expression>> {
        client.stream("KRPC", "Expression_static_Count", &[codec::arg(0, &arg)]).await
    }

    /// Sum all elements of a collection.
    ///
    /// # Arguments
    ///
    /// * `arg` - The list or set.
    ///
    /// # Returns
    ///
    /// The sum of the elements in the collection.
    pub async fn sum(client: &crate::ClientRef, arg: &Expression) -> crate::Result<Expression> {
        let data = client.invoke("KRPC", "Expression_static_Sum", &[codec::arg(0, &arg)]).await?;
        Decode::decode_krpc(client, &data)
    }

    /// Streamed variant of `sum`: the server pushes the value
    /// at the stream's update rate instead of being polled.
    pub async fn sum_stream(client: &crate::ClientRef, arg: &Expression) -> crate::Result<crate::Stream<Expression>> {
        client.stream("KRPC", "Expression_static_Sum", &[codec::arg(0, &arg)]).await
    }

    /// Maximum of all elements in a collection.
    ///
    /// # Arguments
    ///
    /// * `arg` - The list or set.
    ///
    /// # Returns
    ///
    /// The maximum elements in the collection.
    pub async fn max(client: &crate::ClientRef, arg: &Expression) -> crate::Result<Expression> {
        let data = client.invoke("KRPC", "Expression_static_Max", &[codec::arg(0, &arg)]).await?;
        Decode::decode_krpc(client, &data)
    }

    /// Streamed variant of `max`: the server pushes the value
    /// at the stream's update rate instead of being polled.
    pub async fn max_stream(client: &crate::ClientRef, arg: &Expression) -> crate::Result<crate::Stream<Expression>> {
        client.stream("KRPC", "Expression_static_Max", &[codec::arg(0, &arg)]).await
    }

    /// Minimum of all elements in a collection.
    ///
    /// # Arguments
    ///
    /// * `arg` - The list or set.
    ///
    /// # Returns
    ///
    /// The minimum elements in the collection.
    pub async fn min(client: &crate::ClientRef, arg: &Expression) -> crate::Result<Expression> {
        let data = client.invoke("KRPC", "Expression_static_Min", &[codec::arg(0, &arg)]).await?;
        Decode::decode_krpc(client, &data)
    }

    /// Streamed variant of `min`: the server pushes the value
    /// at the stream's update rate instead of being polled.
    pub async fn min_stream(client: &crate::ClientRef, arg: &Expression) -> crate::Result<crate::Stream<Expression>> {
        client.stream("KRPC", "Expression_static_Min", &[codec::arg(0, &arg)]).await
    }

    /// Minimum of all elements in a collection.
    ///
    /// # Arguments
    ///
    /// * `arg` - The list or set.
    ///
    /// # Returns
    ///
    /// The minimum elements in the collection.
    pub async fn average(client: &crate::ClientRef, arg: &Expression) -> crate::Result<Expression> {
        let data = client.invoke("KRPC", "Expression_static_Average", &[codec::arg(0, &arg)]).await?;
        Decode::decode_krpc(client, &data)
    }

    /// Streamed variant of `average`: the server pushes the value
    /// at the stream's update rate instead of being polled.
    pub async fn average_stream(client: &crate::ClientRef, arg: &Expression) -> crate::Result<crate::Stream<Expression>> {
        client.stream("KRPC", "Expression_static_Average", &[codec::arg(0, &arg)]).await
    }

    /// Run a function on every element in the collection.
    ///
    /// # Arguments
    ///
    /// * `arg` - The list or set.
    /// * `func` - The function.
    ///
    /// # Returns
    ///
    /// The modified collection.
    pub async fn select(client: &crate::ClientRef, arg: &Expression, func: &Expression) -> crate::Result<Expression> {
        let data = client.invoke("KRPC", "Expression_static_Select", &[codec::arg(0, &arg), codec::arg(1, &func)]).await?;
        Decode::decode_krpc(client, &data)
    }

    /// Streamed variant of `select`: the server pushes the value
    /// at the stream's update rate instead of being polled.
    pub async fn select_stream(client: &crate::ClientRef, arg: &Expression, func: &Expression) -> crate::Result<crate::Stream<Expression>> {
        client.stream("KRPC", "Expression_static_Select", &[codec::arg(0, &arg), codec::arg(1, &func)]).await
    }

    /// Run a function on every element in the collection.
    ///
    /// # Arguments
    ///
    /// * `arg` - The list or set.
    /// * `func` - The function.
    ///
    /// # Returns
    ///
    /// The modified collection.
    pub async fn r#where(client: &crate::ClientRef, arg: &Expression, func: &Expression) -> crate::Result<Expression> {
        let data = client.invoke("KRPC", "Expression_static_Where", &[codec::arg(0, &arg), codec::arg(1, &func)]).await?;
        Decode::decode_krpc(client, &data)
    }

    /// Streamed variant of `r#where`: the server pushes the value
    /// at the stream's update rate instead of being polled.
    pub async fn r#where_stream(client: &crate::ClientRef, arg: &Expression, func: &Expression) -> crate::Result<crate::Stream<Expression>> {
        client.stream("KRPC", "Expression_static_Where", &[codec::arg(0, &arg), codec::arg(1, &func)]).await
    }

    /// Determine if a collection contains a value.
    ///
    /// # Arguments
    ///
    /// * `arg` - The collection.
    /// * `value` - The value to look for.
    ///
    /// # Returns
    ///
    /// Whether the collection contains a value.
    pub async fn contains(client: &crate::ClientRef, arg: &Expression, value: &Expression) -> crate::Result<Expression> {
        let data = client.invoke("KRPC", "Expression_static_Contains", &[codec::arg(0, &arg), codec::arg(1, &value)]).await?;
        Decode::decode_krpc(client, &data)
    }

    /// Streamed variant of `contains`: the server pushes the value
    /// at the stream's update rate instead of being polled.
    pub async fn contains_stream(client: &crate::ClientRef, arg: &Expression, value: &Expression) -> crate::Result<crate::Stream<Expression>> {
        client.stream("KRPC", "Expression_static_Contains", &[codec::arg(0, &arg), codec::arg(1, &value)]).await
    }

    /// Applies an accumulator function over a sequence.
    ///
    /// # Arguments
    ///
    /// * `arg` - The collection.
    /// * `func` - The accumulator function.
    ///
    /// # Returns
    ///
    /// The accumulated value.
    pub async fn aggregate(client: &crate::ClientRef, arg: &Expression, func: &Expression) -> crate::Result<Expression> {
        let data = client.invoke("KRPC", "Expression_static_Aggregate", &[codec::arg(0, &arg), codec::arg(1, &func)]).await?;
        Decode::decode_krpc(client, &data)
    }

    /// Streamed variant of `aggregate`: the server pushes the value
    /// at the stream's update rate instead of being polled.
    pub async fn aggregate_stream(client: &crate::ClientRef, arg: &Expression, func: &Expression) -> crate::Result<crate::Stream<Expression>> {
        client.stream("KRPC", "Expression_static_Aggregate", &[codec::arg(0, &arg), codec::arg(1, &func)]).await
    }

    /// Applies an accumulator function over a sequence, with a given seed.
    ///
    /// # Arguments
    ///
    /// * `arg` - The collection.
    /// * `seed` - The seed value.
    /// * `func` - The accumulator function.
    ///
    /// # Returns
    ///
    /// The accumulated value.
    pub async fn aggregate_with_seed(client: &crate::ClientRef, arg: &Expression, seed: &Expression, func: &Expression) -> crate::Result<Expression> {
        let data = client.invoke("KRPC", "Expression_static_AggregateWithSeed", &[codec::arg(0, &arg), codec::arg(1, &seed), codec::arg(2, &func)]).await?;
        Decode::decode_krpc(client, &data)
    }

    /// Streamed variant of `aggregate_with_seed`: the server pushes the value
    /// at the stream's update rate instead of being polled.
    pub async fn aggregate_with_seed_stream(client: &crate::ClientRef, arg: &Expression, seed: &Expression, func: &Expression) -> crate::Result<crate::Stream<Expression>> {
        client.stream("KRPC", "Expression_static_AggregateWithSeed", &[codec::arg(0, &arg), codec::arg(1, &seed), codec::arg(2, &func)]).await
    }

    /// Concatenate two sequences.
    ///
    /// # Arguments
    ///
    /// * `arg1` - The first sequence.
    /// * `arg2` - The second sequence.
    ///
    /// # Returns
    ///
    /// The first sequence followed by the second sequence.
    pub async fn concat(client: &crate::ClientRef, arg1: &Expression, arg2: &Expression) -> crate::Result<Expression> {
        let data = client.invoke("KRPC", "Expression_static_Concat", &[codec::arg(0, &arg1), codec::arg(1, &arg2)]).await?;
        Decode::decode_krpc(client, &data)
    }

    /// Streamed variant of `concat`: the server pushes the value
    /// at the stream's update rate instead of being polled.
    pub async fn concat_stream(client: &crate::ClientRef, arg1: &Expression, arg2: &Expression) -> crate::Result<crate::Stream<Expression>> {
        client.stream("KRPC", "Expression_static_Concat", &[codec::arg(0, &arg1), codec::arg(1, &arg2)]).await
    }

    /// Order a collection using a key function.
    ///
    /// # Arguments
    ///
    /// * `arg` - The collection to order.
    /// * `key` - A function that takes a value from the collection and generates a key to sort on.
    ///
    /// # Returns
    ///
    /// The ordered collection.
    pub async fn order_by(client: &crate::ClientRef, arg: &Expression, key: &Expression) -> crate::Result<Expression> {
        let data = client.invoke("KRPC", "Expression_static_OrderBy", &[codec::arg(0, &arg), codec::arg(1, &key)]).await?;
        Decode::decode_krpc(client, &data)
    }

    /// Streamed variant of `order_by`: the server pushes the value
    /// at the stream's update rate instead of being polled.
    pub async fn order_by_stream(client: &crate::ClientRef, arg: &Expression, key: &Expression) -> crate::Result<crate::Stream<Expression>> {
        client.stream("KRPC", "Expression_static_OrderBy", &[codec::arg(0, &arg), codec::arg(1, &key)]).await
    }

    /// Determine whether all items in a collection satisfy a boolean predicate.
    ///
    /// # Arguments
    ///
    /// * `arg` - The collection.
    /// * `predicate` - The predicate function.
    ///
    /// # Returns
    ///
    /// Whether all items satisfy the predicate.
    pub async fn all(client: &crate::ClientRef, arg: &Expression, predicate: &Expression) -> crate::Result<Expression> {
        let data = client.invoke("KRPC", "Expression_static_All", &[codec::arg(0, &arg), codec::arg(1, &predicate)]).await?;
        Decode::decode_krpc(client, &data)
    }

    /// Streamed variant of `all`: the server pushes the value
    /// at the stream's update rate instead of being polled.
    pub async fn all_stream(client: &crate::ClientRef, arg: &Expression, predicate: &Expression) -> crate::Result<crate::Stream<Expression>> {
        client.stream("KRPC", "Expression_static_All", &[codec::arg(0, &arg), codec::arg(1, &predicate)]).await
    }

    /// Determine whether any item in a collection satisfies a boolean predicate.
    ///
    /// # Arguments
    ///
    /// * `arg` - The collection.
    /// * `predicate` - The predicate function.
    ///
    /// # Returns
    ///
    /// Whether any item satisfies the predicate.
    pub async fn any(client: &crate::ClientRef, arg: &Expression, predicate: &Expression) -> crate::Result<Expression> {
        let data = client.invoke("KRPC", "Expression_static_Any", &[codec::arg(0, &arg), codec::arg(1, &predicate)]).await?;
        Decode::decode_krpc(client, &data)
    }

    /// Streamed variant of `any`: the server pushes the value
    /// at the stream's update rate instead of being polled.
    pub async fn any_stream(client: &crate::ClientRef, arg: &Expression, predicate: &Expression) -> crate::Result<crate::Stream<Expression>> {
        client.stream("KRPC", "Expression_static_Any", &[codec::arg(0, &arg), codec::arg(1, &predicate)]).await
    }
}

impl PartialEq for Expression {
    fn eq(&self, other: &Self) -> bool {
        self.id == other.id
    }
}

impl Eq for Expression {}

impl std::hash::Hash for Expression {
    fn hash<H: std::hash::Hasher>(&self, state: &mut H) {
        self.id.hash(state);
    }
}

impl Encode for Expression {
    fn encode_krpc(&self) -> Vec<u8> {
        self.id.encode_krpc()
    }
}

impl Decode for Expression {
    fn decode_krpc(client: &crate::ClientRef, bytes: &[u8]) -> crate::Result<Self> {
        let id = <u64 as Decode>::decode_krpc(client, bytes)?;
        Ok(Self::new(client.clone(), id))
    }
}

impl Decode for Option<Expression> {
    fn decode_krpc(client: &crate::ClientRef, bytes: &[u8]) -> crate::Result<Self> {
        let id = <u64 as Decode>::decode_krpc(client, bytes)?;
        Ok(if id == 0 { None } else { Some(Expression::new(client.clone(), id)) })
    }
}

/// A server side expression.
///
/// A remote object handle for a `KRPC.Type` instance.
#[derive(Debug, Clone)]
pub struct Type {
    #[allow(dead_code)]
    client: crate::ClientRef,
    pub(crate) id: u64,
}

impl Type {
    pub(crate) fn new(client: crate::ClientRef, id: u64) -> Self {
        Self { client, id }
    }

    /// The id of the remote object this handle refers to.
    pub fn object_id(&self) -> u64 {
        self.id
    }

    /// Double type.
    pub async fn double(client: &crate::ClientRef) -> crate::Result<Type> {
        let data = client.invoke("KRPC", "Type_static_Double", &[]).await?;
        Decode::decode_krpc(client, &data)
    }

    /// Streamed variant of `double`: the server pushes the value
    /// at the stream's update rate instead of being polled.
    pub async fn double_stream(client: &crate::ClientRef) -> crate::Result<crate::Stream<Type>> {
        client.stream("KRPC", "Type_static_Double", &[]).await
    }

    /// Float type.
    pub async fn float(client: &crate::ClientRef) -> crate::Result<Type> {
        let data = client.invoke("KRPC", "Type_static_Float", &[]).await?;
        Decode::decode_krpc(client, &data)
    }

    /// Streamed variant of `float`: the server pushes the value
    /// at the stream's update rate instead of being polled.
    pub async fn float_stream(client: &crate::ClientRef) -> crate::Result<crate::Stream<Type>> {
        client.stream("KRPC", "Type_static_Float", &[]).await
    }

    /// Int type.
    pub async fn int(client: &crate::ClientRef) -> crate::Result<Type> {
        let data = client.invoke("KRPC", "Type_static_Int", &[]).await?;
        Decode::decode_krpc(client, &data)
    }

    /// Streamed variant of `int`: the server pushes the value
    /// at the stream's update rate instead of being polled.
    pub async fn int_stream(client: &crate::ClientRef) -> crate::Result<crate::Stream<Type>> {
        client.stream("KRPC", "Type_static_Int", &[]).await
    }

    /// Bool type.
    pub async fn bool(client: &crate::ClientRef) -> crate::Result<Type> {
        let data = client.invoke("KRPC", "Type_static_Bool", &[]).await?;
        Decode::decode_krpc(client, &data)
    }

    /// Streamed variant of `bool`: the server pushes the value
    /// at the stream's update rate instead of being polled.
    pub async fn bool_stream(client: &crate::ClientRef) -> crate::Result<crate::Stream<Type>> {
        client.stream("KRPC", "Type_static_Bool", &[]).await
    }

    /// String type.
    pub async fn string(client: &crate::ClientRef) -> crate::Result<Type> {
        let data = client.invoke("KRPC", "Type_static_String", &[]).await?;
        Decode::decode_krpc(client, &data)
    }

    /// Streamed variant of `string`: the server pushes the value
    /// at the stream's update rate instead of being polled.
    pub async fn string_stream(client: &crate::ClientRef) -> crate::Result<crate::Stream<Type>> {
        client.stream("KRPC", "Type_static_String", &[]).await
    }
}

impl PartialEq for Type {
    fn eq(&self, other: &Self) -> bool {
        self.id == other.id
    }
}

impl Eq for Type {}

impl std::hash::Hash for Type {
    fn hash<H: std::hash::Hasher>(&self, state: &mut H) {
        self.id.hash(state);
    }
}

impl Encode for Type {
    fn encode_krpc(&self) -> Vec<u8> {
        self.id.encode_krpc()
    }
}

impl Decode for Type {
    fn decode_krpc(client: &crate::ClientRef, bytes: &[u8]) -> crate::Result<Self> {
        let id = <u64 as Decode>::decode_krpc(client, bytes)?;
        Ok(Self::new(client.clone(), id))
    }
}

impl Decode for Option<Type> {
    fn decode_krpc(client: &crate::ClientRef, bytes: &[u8]) -> crate::Result<Self> {
        let id = <u64 as Decode>::decode_krpc(client, bytes)?;
        Ok(if id == 0 { None } else { Some(Type::new(client.clone(), id)) })
    }
}

/// Main kRPC service, used by clients to interact with basic server functionality.
pub struct KRPC {
    client: crate::ClientRef,
}

impl KRPC {
    pub fn new(client: crate::ClientRef) -> Self {
        Self { client }
    }

    /// A list of RPC clients that are currently connected to the server. Each entry in the list is a clients identifier, name and address.
    pub async fn clients(&self) -> crate::Result<Vec<(Vec<u8>, String, String)>> {
        let data = self.client.invoke("KRPC", "get_Clients", &[]).await?;
        Decode::decode_krpc(&self.client, &data)
    }

    /// Streamed variant of `clients`: the server pushes the value
    /// at the stream's update rate instead of being polled.
    pub async fn clients_stream(&self) -> crate::Result<crate::Stream<Vec<(Vec<u8>, String, String)>>> {
        self.client.stream("KRPC", "get_Clients", &[]).await
    }

    /// Get the current game scene.
    pub async fn current_game_scene(&self) -> crate::Result<GameScene> {
        let data = self.client.invoke("KRPC", "get_CurrentGameScene", &[]).await?;
        Decode::decode_krpc(&self.client, &data)
    }

    /// Streamed variant of `current_game_scene`: the server pushes the value
    /// at the stream's update rate instead of being polled.
    pub async fn current_game_scene_stream(&self) -> crate::Result<crate::Stream<GameScene>> {
        self.client.stream("KRPC", "get_CurrentGameScene", &[]).await
    }

    /// Whether the game is paused.
    pub async fn paused(&self) -> crate::Result<bool> {
        let data = self.client.invoke("KRPC", "get_Paused", &[]).await?;
        Decode::decode_krpc(&self.client, &data)
    }

    /// Streamed variant of `paused`: the server pushes the value
    /// at the stream's update rate instead of being polled.
    pub async fn paused_stream(&self) -> crate::Result<crate::Stream<bool>> {
        self.client.stream("KRPC", "get_Paused", &[]).await
    }

    /// Whether the game is paused.
    pub async fn set_paused(&self, value: bool) -> crate::Result<()> {
        self.client.invoke("KRPC", "set_Paused", &[codec::arg(0, &value)]).await?;
        Ok(())
    }

    /// Returns the identifier for the current client.
    pub async fn get_client_id(&self) -> crate::Result<Vec<u8>> {
        let data = self.client.invoke("KRPC", "GetClientID", &[]).await?;
        Decode::decode_krpc(&self.client, &data)
    }

    /// Streamed variant of `get_client_id`: the server pushes the value
    /// at the stream's update rate instead of being polled.
    pub async fn get_client_id_stream(&self) -> crate::Result<crate::Stream<Vec<u8>>> {
        self.client.stream("KRPC", "GetClientID", &[]).await
    }

    /// Returns the name of the current client. This is an empty string if the client has no name.
    pub async fn get_client_name(&self) -> crate::Result<String> {
        let data = self.client.invoke("KRPC", "GetClientName", &[]).await?;
        Decode::decode_krpc(&self.client, &data)
    }

    /// Streamed variant of `get_client_name`: the server pushes the value
    /// at the stream's update rate instead of being polled.
    pub async fn get_client_name_stream(&self) -> crate::Result<crate::Stream<String>> {
        self.client.stream("KRPC", "GetClientName", &[]).await
    }

    /// Returns some information about the server, such as the version.
    pub async fn get_status(&self) -> crate::Result<crate::krpc::schema::Status> {
        let data = self.client.invoke("KRPC", "GetStatus", &[]).await?;
        Decode::decode_krpc(&self.client, &data)
    }

    /// Streamed variant of `get_status`: the server pushes the value
    /// at the stream's update rate instead of being polled.
    pub async fn get_status_stream(&self) -> crate::Result<crate::Stream<crate::krpc::schema::Status>> {
        self.client.stream("KRPC", "GetStatus", &[]).await
    }

    /// Returns information on all services, procedures, classes, properties etc. provided by the server. Can be used by client libraries to automatically create functionality such as stubs.
    pub async fn get_services(&self) -> crate::Result<crate::krpc::schema::Services> {
        let data = self.client.invoke("KRPC", "GetServices", &[]).await?;
        Decode::decode_krpc(&self.client, &data)
    }

    /// Streamed variant of `get_services`: the server pushes the value
    /// at the stream's update rate instead of being polled.
    pub async fn get_services_stream(&self) -> crate::Result<crate::Stream<crate::krpc::schema::Services>> {
        self.client.stream("KRPC", "GetServices", &[]).await
    }

    /// Add a streaming request and return its identifier.
    pub async fn add_stream(&self, call: &crate::krpc::schema::ProcedureCall, start: Option<bool>) -> crate::Result<crate::krpc::schema::Stream> {
        let mut args = vec![codec::arg(0, &call)];
        if let Some(v) = &start {
            args.push(codec::arg(1, v));
        }
        let data = self.client.invoke("KRPC", "AddStream", &args).await?;
        Decode::decode_krpc(&self.client, &data)
    }

    /// Streamed variant of `add_stream`: the server pushes the value
    /// at the stream's update rate instead of being polled.
    pub async fn add_stream_stream(&self, call: &crate::krpc::schema::ProcedureCall, start: Option<bool>) -> crate::Result<crate::Stream<crate::krpc::schema::Stream>> {
        let mut args = vec![codec::arg(0, &call)];
        if let Some(v) = &start {
            args.push(codec::arg(1, v));
        }
        self.client.stream("KRPC", "AddStream", &args).await
    }

    /// Start a previously added streaming request.
    pub async fn start_stream(&self, id: u64) -> crate::Result<()> {
        self.client.invoke("KRPC", "StartStream", &[codec::arg(0, &id)]).await?;
        Ok(())
    }

    /// Set the update rate for a stream in Hz.
    pub async fn set_stream_rate(&self, id: u64, rate: f32) -> crate::Result<()> {
        self.client.invoke("KRPC", "SetStreamRate", &[codec::arg(0, &id), codec::arg(1, &rate)]).await?;
        Ok(())
    }

    /// Remove a streaming request.
    pub async fn remove_stream(&self, id: u64) -> crate::Result<()> {
        self.client.invoke("KRPC", "RemoveStream", &[codec::arg(0, &id)]).await?;
        Ok(())
    }

    /// Create an event from a server side expression.
    pub async fn add_event(&self, expression: &Expression) -> crate::Result<crate::krpc::schema::Event> {
        let data = self.client.invoke("KRPC", "AddEvent", &[codec::arg(0, &expression)]).await?;
        Decode::decode_krpc(&self.client, &data)
    }

    /// Streamed variant of `add_event`: the server pushes the value
    /// at the stream's update rate instead of being polled.
    pub async fn add_event_stream(&self, expression: &Expression) -> crate::Result<crate::Stream<crate::krpc::schema::Event>> {
        self.client.stream("KRPC", "AddEvent", &[codec::arg(0, &expression)]).await
    }
}
