// Generated by stayputnik-codegen. Do not edit.

//! LaserDist Service

use crate::codec::{self, Decode, Encode};

/// A LaserDist laser.
///
/// A remote object handle for a `LiDAR.Laser` instance.
#[derive(Debug, Clone)]
pub struct Laser {
    client: crate::ClientRef,
    pub(crate) id: u64,
}

impl Laser {
    pub(crate) fn new(client: crate::ClientRef, id: u64) -> Self {
        Self { client, id }
    }

    /// Get the pointcloud.
    pub async fn cloud(&self) -> crate::Result<Vec<f64>> {
        let data = self.client.invoke("LiDAR", "Laser_get_Cloud", &[codec::arg(0, &self.id)]).await?;
        Decode::decode_krpc(&self.client, &data)
    }

    /// Streamed variant of `cloud`: the server pushes the value
    /// at the stream's update rate instead of being polled.
    pub async fn cloud_stream(&self) -> crate::Result<crate::Stream<Vec<f64>>> {
        self.client.stream("LiDAR", "Laser_get_Cloud", &[codec::arg(0, &self.id)]).await
    }

    /// Get the part containing this LiDAR.
    pub async fn part(&self) -> crate::Result<super::space_center::Part> {
        let data = self.client.invoke("LiDAR", "Laser_get_Part", &[codec::arg(0, &self.id)]).await?;
        Decode::decode_krpc(&self.client, &data)
    }

    /// Streamed variant of `part`: the server pushes the value
    /// at the stream's update rate instead of being polled.
    pub async fn part_stream(&self) -> crate::Result<crate::Stream<super::space_center::Part>> {
        self.client.stream("LiDAR", "Laser_get_Part", &[codec::arg(0, &self.id)]).await
    }
}

impl PartialEq for Laser {
    fn eq(&self, other: &Self) -> bool {
        self.id == other.id
    }
}

impl Eq for Laser {}

impl std::hash::Hash for Laser {
    fn hash<H: std::hash::Hasher>(&self, state: &mut H) {
        self.id.hash(state);
    }
}

impl Encode for Laser {
    fn encode_krpc(&self) -> Vec<u8> {
        self.id.encode_krpc()
    }
}

impl Decode for Laser {
    fn decode_krpc(client: &crate::ClientRef, bytes: &[u8]) -> crate::Result<Self> {
        let id = <u64 as Decode>::decode_krpc(client, bytes)?;
        Ok(Self::new(client.clone(), id))
    }
}

impl Decode for Option<Laser> {
    fn decode_krpc(client: &crate::ClientRef, bytes: &[u8]) -> crate::Result<Self> {
        let id = <u64 as Decode>::decode_krpc(client, bytes)?;
        Ok(if id == 0 { None } else { Some(Laser::new(client.clone(), id)) })
    }
}

/// LaserDist Service
pub struct LiDAR {
    client: crate::ClientRef,
}

impl LiDAR {
    pub fn new(client: crate::ClientRef) -> Self {
        Self { client }
    }

    /// Check if the LaserDist API is avaiable
    pub async fn available(&self) -> crate::Result<bool> {
        let data = self.client.invoke("LiDAR", "get_Available", &[]).await?;
        Decode::decode_krpc(&self.client, &data)
    }

    /// Streamed variant of `available`: the server pushes the value
    /// at the stream's update rate instead of being polled.
    pub async fn available_stream(&self) -> crate::Result<crate::Stream<bool>> {
        self.client.stream("LiDAR", "get_Available", &[]).await
    }

    /// Get a LaserDist part
    pub async fn laser(&self, part: &super::space_center::Part) -> crate::Result<Laser> {
        let data = self.client.invoke("LiDAR", "Laser", &[codec::arg(0, &part)]).await?;
        Decode::decode_krpc(&self.client, &data)
    }

    /// Streamed variant of `laser`: the server pushes the value
    /// at the stream's update rate instead of being polled.
    pub async fn laser_stream(&self, part: &super::space_center::Part) -> crate::Result<crate::Stream<Laser>> {
        self.client.stream("LiDAR", "Laser", &[codec::arg(0, &part)]).await
    }
}
