// Generated by stayputnik-codegen. Do not edit.

//! Generated bindings for every service the kRPC server exposes.
//!
//! Each kRPC service becomes a module, and within it:
//!
//! - the **service** itself is a struct (e.g. `space_center::SpaceCenter`)
//!   constructed from a [`ClientRef`](crate::ClientRef), with the service's
//!   procedures and properties as async methods;
//! - **remote classes** are handle structs (e.g. `space_center::Vessel`)
//!   that refer to an object living on the server. Handles are cheap to
//!   clone, and compare/hash by remote object identity. Their properties
//!   and methods are async; static methods take a `ClientRef`;
//! - **enumerations** are Rust enums;
//! - every value-returning method has a `*_stream()` twin returning a
//!   [`Stream`](crate::Stream) that the server pushes updates to.
//!
//! Property getters keep the property's name (`vessel.name()`); setters are
//! prefixed (`vessel.set_name(..)`). Methods taking optional parameters
//! (those with server-side defaults) take `Option`s; passing `None` uses
//! the server's default.
//!
//! These bindings are a snapshot of one server's `KRPC.GetServices`
//! response (see `proto/services.bin`), so the available modules depend on
//! the mods installed when it was captured. To regenerate against your own
//! server: `stayputnik-codegen capture <address>` then
//! `stayputnik-codegen generate`.

pub mod docking_camera;
pub mod drawing;
pub mod infernal_robotics;
pub mod kerbal_alarm_clock;
pub mod krpc;
pub mod lidar;
pub mod remote_tech;
pub mod space_center;
pub mod ui;
