// Generated by stayputnik-codegen. Do not edit.

//! Provides functionality for drawing and interacting with in-game user interface elements.
//!
//! For drawing 3D objects in the flight scene, see the Drawing service.

use crate::codec::{self, Decode, Encode};

/// Font style.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
#[repr(i32)]
pub enum FontStyle {
    /// Normal.
    Normal = 0,
    /// Bold.
    Bold = 1,
    /// Italic.
    Italic = 2,
    /// Bold and italic.
    BoldAndItalic = 3,
}

impl TryFrom<i32> for FontStyle {
    type Error = crate::Error;

    fn try_from(value: i32) -> Result<Self, Self::Error> {
        match value {
            0 => Ok(Self::Normal),
            1 => Ok(Self::Bold),
            2 => Ok(Self::Italic),
            3 => Ok(Self::BoldAndItalic),
            _ => Err(crate::Error::Decode(prost::DecodeError::new(format!("unknown enum value {} for FontStyle", value)))),
        }
    }
}

impl Encode for FontStyle {
    fn encode_krpc(&self) -> Vec<u8> {
        (*self as i32).encode_krpc()
    }
}

impl Decode for FontStyle {
    fn decode_krpc(client: &crate::ClientRef, bytes: &[u8]) -> crate::Result<Self> {
        Self::try_from(<i32 as Decode>::decode_krpc(client, bytes)?)
    }
}

/// Message position.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
#[repr(i32)]
pub enum MessagePosition {
    /// Bottom center.
    BottomCenter = 0,
    /// Top center.
    TopCenter = 1,
    /// Top left.
    TopLeft = 2,
    /// Top right.
    TopRight = 3,
}

impl TryFrom<i32> for MessagePosition {
    type Error = crate::Error;

    fn try_from(value: i32) -> Result<Self, Self::Error> {
        match value {
            0 => Ok(Self::BottomCenter),
            1 => Ok(Self::TopCenter),
            2 => Ok(Self::TopLeft),
            3 => Ok(Self::TopRight),
            _ => Err(crate::Error::Decode(prost::DecodeError::new(format!("unknown enum value {} for MessagePosition", value)))),
        }
    }
}

impl Encode for MessagePosition {
    fn encode_krpc(&self) -> Vec<u8> {
        (*self as i32).encode_krpc()
    }
}

impl Decode for MessagePosition {
    fn decode_krpc(client: &crate::ClientRef, bytes: &[u8]) -> crate::Result<Self> {
        Self::try_from(<i32 as Decode>::decode_krpc(client, bytes)?)
    }
}

/// Text alignment.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
#[repr(i32)]
pub enum TextAlignment {
    /// Left aligned.
    Left = 0,
    /// Right aligned.
    Right = 1,
    /// Center aligned.
    Center = 2,
}

impl TryFrom<i32> for TextAlignment {
    type Error = crate::Error;

    fn try_from(value: i32) -> Result<Self, Self::Error> {
        match value {
            0 => Ok(Self::Left),
            1 => Ok(Self::Right),
            2 => Ok(Self::Center),
            _ => Err(crate::Error::Decode(prost::DecodeError::new(format!("unknown enum value {} for TextAlignment", value)))),
        }
    }
}

impl Encode for TextAlignment {
    fn encode_krpc(&self) -> Vec<u8> {
        (*self as i32).encode_krpc()
    }
}

impl Decode for TextAlignment {
    fn decode_krpc(client: &crate::ClientRef, bytes: &[u8]) -> crate::Result<Self> {
        Self::try_from(<i32 as Decode>::decode_krpc(client, bytes)?)
    }
}

/// Text alignment.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
#[repr(i32)]
pub enum TextAnchor {
    /// Lower center.
    LowerCenter = 0,
    /// Lower left.
    LowerLeft = 1,
    /// Lower right.
    LowerRight = 2,
    /// Middle center.
    MiddleCenter = 3,
    /// Middle left.
    MiddleLeft = 4,
    /// Middle right.
    MiddleRight = 5,
    /// Upper center.
    UpperCenter = 6,
    /// Upper left.
    UpperLeft = 7,
    /// Upper right.
    UpperRight = 8,
}

impl TryFrom<i32> for TextAnchor {
    type Error = crate::Error;

    fn try_from(value: i32) -> Result<Self, Self::Error> {
        match value {
            0 => Ok(Self::LowerCenter),
            1 => Ok(Self::LowerLeft),
            2 => Ok(Self::LowerRight),
            3 => Ok(Self::MiddleCenter),
            4 => Ok(Self::MiddleLeft),
            5 => Ok(Self::MiddleRight),
            6 => Ok(Self::UpperCenter),
            7 => Ok(Self::UpperLeft),
            8 => Ok(Self::UpperRight),
            _ => Err(crate::Error::Decode(prost::DecodeError::new(format!("unknown enum value {} for TextAnchor", value)))),
        }
    }
}

impl Encode for TextAnchor {
    fn encode_krpc(&self) -> Vec<u8> {
        (*self as i32).encode_krpc()
    }
}

impl Decode for TextAnchor {
    fn decode_krpc(client: &crate::ClientRef, bytes: &[u8]) -> crate::Result<Self> {
        Self::try_from(<i32 as Decode>::decode_krpc(client, bytes)?)
    }
}

/// A text label. See `UI.Panel.AddButton`.
///
/// A remote object handle for a `UI.Button` instance.
#[derive(Debug, Clone)]
pub struct Button {
    client: crate::ClientRef,
    pub(crate) id: u64,
}

impl Button {
    pub(crate) fn new(client: crate::ClientRef, id: u64) -> Self {
        Self { client, id }
    }

    /// Whether the button has been clicked.
    ///
    /// This property is set to true when the user clicks the button. A client script should reset the property to false in order to detect subsequent button presses.
    pub async fn clicked(&self) -> crate::Result<bool> {
        let data = self.client.invoke("UI", "Button_get_Clicked", &[codec::arg(0, &self.id)]).await?;
        Decode::decode_krpc(&self.client, &data)
    }

    /// Streamed variant of `clicked`: the server pushes the value
    /// at the stream's update rate instead of being polled.
    pub async fn clicked_stream(&self) -> crate::Result<crate::Stream<bool>> {
        self.client.stream("UI", "Button_get_Clicked", &[codec::arg(0, &self.id)]).await
    }

    /// The rect transform for the text.
    pub async fn rect_transform(&self) -> crate::Result<RectTransform> {
        let data = self.client.invoke("UI", "Button_get_RectTransform", &[codec::arg(0, &self.id)]).await?;
        Decode::decode_krpc(&self.client, &data)
    }

    /// Streamed variant of `rect_transform`: the server pushes the value
    /// at the stream's update rate instead of being polled.
    pub async fn rect_transform_stream(&self) -> crate::Result<crate::Stream<RectTransform>> {
        self.client.stream("UI", "Button_get_RectTransform", &[codec::arg(0, &self.id)]).await
    }

    /// The text for the button.
    pub async fn text(&self) -> crate::Result<Text> {
        let data = self.client.invoke("UI", "Button_get_Text", &[codec::arg(0, &self.id)]).await?;
        Decode::decode_krpc(&self.client, &data)
    }

    /// Streamed variant of `text`: the server pushes the value
    /// at the stream's update rate instead of being polled.
    pub async fn text_stream(&self) -> crate::Result<crate::Stream<Text>> {
        self.client.stream("UI", "Button_get_Text", &[codec::arg(0, &self.id)]).await
    }

    /// Whether the UI object is visible.
    pub async fn visible(&self) -> crate::Result<bool> {
        let data = self.client.invoke("UI", "Button_get_Visible", &[codec::arg(0, &self.id)]).await?;
        Decode::decode_krpc(&self.client, &data)
    }

    /// Streamed variant of `visible`: the server pushes the value
    /// at the stream's update rate instead of being polled.
    pub async fn visible_stream(&self) -> crate::Result<crate::Stream<bool>> {
        self.client.stream("UI", "Button_get_Visible", &[codec::arg(0, &self.id)]).await
    }

    /// Whether the button has been clicked.
    ///
    /// This property is set to true when the user clicks the button. A client script should reset the property to false in order to detect subsequent button presses.
    pub async fn set_clicked(&self, value: bool) -> crate::Result<()> {
        self.client.invoke("UI", "Button_set_Clicked", &[codec::arg(0, &self.id), codec::arg(1, &value)]).await?;
        Ok(())
    }

    /// Whether the UI object is visible.
    pub async fn set_visible(&self, value: bool) -> crate::Result<()> {
        self.client.invoke("UI", "Button_set_Visible", &[codec::arg(0, &self.id), codec::arg(1, &value)]).await?;
        Ok(())
    }

    /// Remove the UI object.
    pub async fn remove(&self) -> crate::Result<()> {
        self.client.invoke("UI", "Button_Remove", &[codec::arg(0, &self.id)]).await?;
        Ok(())
    }
}

impl PartialEq for Button {
    fn eq(&self, other: &Self) -> bool {
        self.id == other.id
    }
}

impl Eq for Button {}

impl std::hash::Hash for Button {
    fn hash<H: std::hash::Hasher>(&self, state: &mut H) {
        self.id.hash(state);
    }
}

impl Encode for Button {
    fn encode_krpc(&self) -> Vec<u8> {
        self.id.encode_krpc()
    }
}

impl Decode for Button {
    fn decode_krpc(client: &crate::ClientRef, bytes: &[u8]) -> crate::Result<Self> {
        let id = <u64 as Decode>::decode_krpc(client, bytes)?;
        Ok(Self::new(client.clone(), id))
    }
}

impl Decode for Option<Button> {
    fn decode_krpc(client: &crate::ClientRef, bytes: &[u8]) -> crate::Result<Self> {
        let id = <u64 as Decode>::decode_krpc(client, bytes)?;
        Ok(if id == 0 { None } else { Some(Button::new(client.clone(), id)) })
    }
}

/// A canvas for user interface elements. See `UI.StockCanvas` and `UI.AddCanvas`.
///
/// A remote object handle for a `UI.Canvas` instance.
#[derive(Debug, Clone)]
pub struct Canvas {
    client: crate::ClientRef,
    pub(crate) id: u64,
}

impl Canvas {
    pub(crate) fn new(client: crate::ClientRef, id: u64) -> Self {
        Self { client, id }
    }

    /// The rect transform for the canvas.
    pub async fn rect_transform(&self) -> crate::Result<RectTransform> {
        let data = self.client.invoke("UI", "Canvas_get_RectTransform", &[codec::arg(0, &self.id)]).await?;
        Decode::decode_krpc(&self.client, &data)
    }

    /// Streamed variant of `rect_transform`: the server pushes the value
    /// at the stream's update rate instead of being polled.
    pub async fn rect_transform_stream(&self) -> crate::Result<crate::Stream<RectTransform>> {
        self.client.stream("UI", "Canvas_get_RectTransform", &[codec::arg(0, &self.id)]).await
    }

    /// Whether the UI object is visible.
    pub async fn visible(&self) -> crate::Result<bool> {
        let data = self.client.invoke("UI", "Canvas_get_Visible", &[codec::arg(0, &self.id)]).await?;
        Decode::decode_krpc(&self.client, &data)
    }

    /// Streamed variant of `visible`: the server pushes the value
    /// at the stream's update rate instead of being polled.
    pub async fn visible_stream(&self) -> crate::Result<crate::Stream<bool>> {
        self.client.stream("UI", "Canvas_get_Visible", &[codec::arg(0, &self.id)]).await
    }

    /// Whether the UI object is visible.
    pub async fn set_visible(&self, value: bool) -> crate::Result<()> {
        self.client.invoke("UI", "Canvas_set_Visible", &[codec::arg(0, &self.id), codec::arg(1, &value)]).await?;
        Ok(())
    }

    /// Create a new container for user interface elements.
    ///
    /// # Arguments
    ///
    /// * `visible` - Whether the panel is visible.
    pub async fn add_panel(&self, visible: Option<bool>) -> crate::Result<Panel> {
        let mut args = vec![codec::arg(0, &self.id)];
        if let Some(v) = &visible {
            args.push(codec::arg(1, v));
        }
        let data = self.client.invoke("UI", "Canvas_AddPanel", &args).await?;
        Decode::decode_krpc(&self.client, &data)
    }

    /// Streamed variant of `add_panel`: the server pushes the value
    /// at the stream's update rate instead of being polled.
    pub async fn add_panel_stream(&self, visible: Option<bool>) -> crate::Result<crate::Stream<Panel>> {
        let mut args = vec![codec::arg(0, &self.id)];
        if let Some(v) = &visible {
            args.push(codec::arg(1, v));
        }
        self.client.stream("UI", "Canvas_AddPanel", &args).await
    }

    /// Add text to the canvas.
    ///
    /// # Arguments
    ///
    /// * `content` - The text.
    /// * `visible` - Whether the text is visible.
    pub async fn add_text(&self, content: &str, visible: Option<bool>) -> crate::Result<Text> {
        let mut args = vec![codec::arg(0, &self.id), codec::arg(1, &content)];
        if let Some(v) = &visible {
            args.push(codec::arg(2, v));
        }
        let data = self.client.invoke("UI", "Canvas_AddText", &args).await?;
        Decode::decode_krpc(&self.client, &data)
    }

    /// Streamed variant of `add_text`: the server pushes the value
    /// at the stream's update rate instead of being polled.
    pub async fn add_text_stream(&self, content: &str, visible: Option<bool>) -> crate::Result<crate::Stream<Text>> {
        let mut args = vec![codec::arg(0, &self.id), codec::arg(1, &content)];
        if let Some(v) = &visible {
            args.push(codec::arg(2, v));
        }
        self.client.stream("UI", "Canvas_AddText", &args).await
    }

    /// Add an input field to the canvas.
    ///
    /// # Arguments
    ///
    /// * `visible` - Whether the input field is visible.
    pub async fn add_input_field(&self, visible: Option<bool>) -> crate::Result<InputField> {
        let mut args = vec![codec::arg(0, &self.id)];
        if let Some(v) = &visible {
            args.push(codec::arg(1, v));
        }
        let data = self.client.invoke("UI", "Canvas_AddInputField", &args).await?;
        Decode::decode_krpc(&self.client, &data)
    }

    /// Streamed variant of `add_input_field`: the server pushes the value
    /// at the stream's update rate instead of being polled.
    pub async fn add_input_field_stream(&self, visible: Option<bool>) -> crate::Result<crate::Stream<InputField>> {
        let mut args = vec![codec::arg(0, &self.id)];
        if let Some(v) = &visible {
            args.push(codec::arg(1, v));
        }
        self.client.stream("UI", "Canvas_AddInputField", &args).await
    }

    /// Add a button to the canvas.
    ///
    /// # Arguments
    ///
    /// * `content` - The label for the button.
    /// * `visible` - Whether the button is visible.
    pub async fn add_button(&self, content: &str, visible: Option<bool>) -> crate::Result<Button> {
        let mut args = vec![codec::arg(0, &self.id), codec::arg(1, &content)];
        if let Some(v) = &visible {
            args.push(codec::arg(2, v));
        }
        let data = self.client.invoke("UI", "Canvas_AddButton", &args).await?;
        Decode::decode_krpc(&self.client, &data)
    }

    /// Streamed variant of `add_button`: the server pushes the value
    /// at the stream's update rate instead of being polled.
    pub async fn add_button_stream(&self, content: &str, visible: Option<bool>) -> crate::Result<crate::Stream<Button>> {
        let mut args = vec![codec::arg(0, &self.id), codec::arg(1, &content)];
        if let Some(v) = &visible {
            args.push(codec::arg(2, v));
        }
        self.client.stream("UI", "Canvas_AddButton", &args).await
    }

    /// Remove the UI object.
    pub async fn remove(&self) -> crate::Result<()> {
        self.client.invoke("UI", "Canvas_Remove", &[codec::arg(0, &self.id)]).await?;
        Ok(())
    }
}

impl PartialEq for Canvas {
    fn eq(&self, other: &Self) -> bool {
        self.id == other.id
    }
}

impl Eq for Canvas {}

impl std::hash::Hash for Canvas {
    fn hash<H: std::hash::Hasher>(&self, state: &mut H) {
        self.id.hash(state);
    }
}

impl Encode for Canvas {
    fn encode_krpc(&self) -> Vec<u8> {
        self.id.encode_krpc()
    }
}

impl Decode for Canvas {
    fn decode_krpc(client: &crate::ClientRef, bytes: &[u8]) -> crate::Result<Self> {
        let id = <u64 as Decode>::decode_krpc(client, bytes)?;
        Ok(Self::new(client.clone(), id))
    }
}

impl Decode for Option<Canvas> {
    fn decode_krpc(client: &crate::ClientRef, bytes: &[u8]) -> crate::Result<Self> {
        let id = <u64 as Decode>::decode_krpc(client, bytes)?;
        Ok(if id == 0 { None } else { Some(Canvas::new(client.clone(), id)) })
    }
}

/// An input field. See `UI.Panel.AddInputField`.
///
/// A remote object handle for a `UI.InputField` instance.
#[derive(Debug, Clone)]
pub struct InputField {
    client: crate::ClientRef,
    pub(crate) id: u64,
}

impl InputField {
    pub(crate) fn new(client: crate::ClientRef, id: u64) -> Self {
        Self { client, id }
    }

    /// Whether the input field has been changed.
    ///
    /// This property is set to true when the user modifies the value of the input field. A client script should reset the property to false in order to detect subsequent changes.
    pub async fn changed(&self) -> crate::Result<bool> {
        let data = self.client.invoke("UI", "InputField_get_Changed", &[codec::arg(0, &self.id)]).await?;
        Decode::decode_krpc(&self.client, &data)
    }

    /// Streamed variant of `changed`: the server pushes the value
    /// at the stream's update rate instead of being polled.
    pub async fn changed_stream(&self) -> crate::Result<crate::Stream<bool>> {
        self.client.stream("UI", "InputField_get_Changed", &[codec::arg(0, &self.id)]).await
    }

    /// The rect transform for the input field.
    pub async fn rect_transform(&self) -> crate::Result<RectTransform> {
        let data = self.client.invoke("UI", "InputField_get_RectTransform", &[codec::arg(0, &self.id)]).await?;
        Decode::decode_krpc(&self.client, &data)
    }

    /// Streamed variant of `rect_transform`: the server pushes the value
    /// at the stream's update rate instead of being polled.
    pub async fn rect_transform_stream(&self) -> crate::Result<crate::Stream<RectTransform>> {
        self.client.stream("UI", "InputField_get_RectTransform", &[codec::arg(0, &self.id)]).await
    }

    /// The text component of the input field.
    ///
    /// Use `UI.InputField.Value` to get and set the value in the field. This object can be used to alter the style of the input field's text.
    pub async fn text(&self) -> crate::Result<Text> {
        let data = self.client.invoke("UI", "InputField_get_Text", &[codec::arg(0, &self.id)]).await?;
        Decode::decode_krpc(&self.client, &data)
    }

    /// Streamed variant of `text`: the server pushes the value
    /// at the stream's update rate instead of being polled.
    pub async fn text_stream(&self) -> crate::Result<crate::Stream<Text>> {
        self.client.stream("UI", "InputField_get_Text", &[codec::arg(0, &self.id)]).await
    }

    /// The value of the input field.
    pub async fn value(&self) -> crate::Result<String> {
        let data = self.client.invoke("UI", "InputField_get_Value", &[codec::arg(0, &self.id)]).await?;
        Decode::decode_krpc(&self.client, &data)
    }

    /// Streamed variant of `value`: the server pushes the value
    /// at the stream's update rate instead of being polled.
    pub async fn value_stream(&self) -> crate::Result<crate::Stream<String>> {
        self.client.stream("UI", "InputField_get_Value", &[codec::arg(0, &self.id)]).await
    }

    /// Whether the UI object is visible.
    pub async fn visible(&self) -> crate::Result<bool> {
        let data = self.client.invoke("UI", "InputField_get_Visible", &[codec::arg(0, &self.id)]).await?;
        Decode::decode_krpc(&self.client, &data)
    }

    /// Streamed variant of `visible`: the server pushes the value
    /// at the stream's update rate instead of being polled.
    pub async fn visible_stream(&self) -> crate::Result<crate::Stream<bool>> {
        self.client.stream("UI", "InputField_get_Visible", &[codec::arg(0, &self.id)]).await
    }

    /// Whether the input field has been changed.
    ///
    /// This property is set to true when the user modifies the value of the input field. A client script should reset the property to false in order to detect subsequent changes.
    pub async fn set_changed(&self, value: bool) -> crate::Result<()> {
        self.client.invoke("UI", "InputField_set_Changed", &[codec::arg(0, &self.id), codec::arg(1, &value)]).await?;
        Ok(())
    }

    /// The value of the input field.
    pub async fn set_value(&self, value: &str) -> crate::Result<()> {
        self.client.invoke("UI", "InputField_set_Value", &[codec::arg(0, &self.id), codec::arg(1, &value)]).await?;
        Ok(())
    }

    /// Whether the UI object is visible.
    pub async fn set_visible(&self, value: bool) -> crate::Result<()> {
        self.client.invoke("UI", "InputField_set_Visible", &[codec::arg(0, &self.id), codec::arg(1, &value)]).await?;
        Ok(())
    }

    /// Remove the UI object.
    pub async fn remove(&self) -> crate::Result<()> {
        self.client.invoke("UI", "InputField_Remove", &[codec::arg(0, &self.id)]).await?;
        Ok(())
    }
}

impl PartialEq for InputField {
    fn eq(&self, other: &Self) -> bool {
        self.id == other.id
    }
}

impl Eq for InputField {}

impl std::hash::Hash for InputField {
    fn hash<H: std::hash::Hasher>(&self, state: &mut H) {
        self.id.hash(state);
    }
}

impl Encode for InputField {
    fn encode_krpc(&self) -> Vec<u8> {
        self.id.encode_krpc()
    }
}

impl Decode for InputField {
    fn decode_krpc(client: &crate::ClientRef, bytes: &[u8]) -> crate::Result<Self> {
        let id = <u64 as Decode>::decode_krpc(client, bytes)?;
        Ok(Self::new(client.clone(), id))
    }
}

impl Decode for Option<InputField> {
    fn decode_krpc(client: &crate::ClientRef, bytes: &[u8]) -> crate::Result<Self> {
        let id = <u64 as Decode>::decode_krpc(client, bytes)?;
        Ok(if id == 0 { None } else { Some(InputField::new(client.clone(), id)) })
    }
}

/// A container for user interface elements. See `UI.Canvas.AddPanel`.
///
/// A remote object handle for a `UI.Panel` instance.
#[derive(Debug, Clone)]
pub struct Panel {
    client: crate::ClientRef,
    pub(crate) id: u64,
}

impl Panel {
    pub(crate) fn new(client: crate::ClientRef, id: u64) -> Self {
        Self { client, id }
    }

    /// The rect transform for the panel.
    pub async fn rect_transform(&self) -> crate::Result<RectTransform> {
        let data = self.client.invoke("UI", "Panel_get_RectTransform", &[codec::arg(0, &self.id)]).await?;
        Decode::decode_krpc(&self.client, &data)
    }

    /// Streamed variant of `rect_transform`: the server pushes the value
    /// at the stream's update rate instead of being polled.
    pub async fn rect_transform_stream(&self) -> crate::Result<crate::Stream<RectTransform>> {
        self.client.stream("UI", "Panel_get_RectTransform", &[codec::arg(0, &self.id)]).await
    }

    /// Whether the UI object is visible.
    pub async fn visible(&self) -> crate::Result<bool> {
        let data = self.client.invoke("UI", "Panel_get_Visible", &[codec::arg(0, &self.id)]).await?;
        Decode::decode_krpc(&self.client, &data)
    }

    /// Streamed variant of `visible`: the server pushes the value
    /// at the stream's update rate instead of being polled.
    pub async fn visible_stream(&self) -> crate::Result<crate::Stream<bool>> {
        self.client.stream("UI", "Panel_get_Visible", &[codec::arg(0, &self.id)]).await
    }

    /// Whether the UI object is visible.
    pub async fn set_visible(&self, value: bool) -> crate::Result<()> {
        self.client.invoke("UI", "Panel_set_Visible", &[codec::arg(0, &self.id), codec::arg(1, &value)]).await?;
        Ok(())
    }

    /// Create a panel within this panel.
    ///
    /// # Arguments
    ///
    /// * `visible` - Whether the new panel is visible.
    pub async fn add_panel(&self, visible: Option<bool>) -> crate::Result<Panel> {
        let mut args = vec![codec::arg(0, &self.id)];
        if let Some(v) = &visible {
            args.push(codec::arg(1, v));
        }
        let data = self.client.invoke("UI", "Panel_AddPanel", &args).await?;
        Decode::decode_krpc(&self.client, &data)
    }

    /// Streamed variant of `add_panel`: the server pushes the value
    /// at the stream's update rate instead of being polled.
    pub async fn add_panel_stream(&self, visible: Option<bool>) -> crate::Result<crate::Stream<Panel>> {
        let mut args = vec![codec::arg(0, &self.id)];
        if let Some(v) = &visible {
            args.push(codec::arg(1, v));
        }
        self.client.stream("UI", "Panel_AddPanel", &args).await
    }

    /// Add text to the panel.
    ///
    /// # Arguments
    ///
    /// * `content` - The text.
    /// * `visible` - Whether the text is visible.
    pub async fn add_text(&self, content: &str, visible: Option<bool>) -> crate::Result<Text> {
        let mut args = vec![codec::arg(0, &self.id), codec::arg(1, &content)];
        if let Some(v) = &visible {
            args.push(codec::arg(2, v));
        }
        let data = self.client.invoke("UI", "Panel_AddText", &args).await?;
        Decode::decode_krpc(&self.client, &data)
    }

    /// Streamed variant of `add_text`: the server pushes the value
    /// at the stream's update rate instead of being polled.
    pub async fn add_text_stream(&self, content: &str, visible: Option<bool>) -> crate::Result<crate::Stream<Text>> {
        let mut args = vec![codec::arg(0, &self.id), codec::arg(1, &content)];
        if let Some(v) = &visible {
            args.push(codec::arg(2, v));
        }
        self.client.stream("UI", "Panel_AddText", &args).await
    }

    /// Add an input field to the panel.
    ///
    /// # Arguments
    ///
    /// * `visible` - Whether the input field is visible.
    pub async fn add_input_field(&self, visible: Option<bool>) -> crate::Result<InputField> {
        let mut args = vec![codec::arg(0, &self.id)];
        if let Some(v) = &visible {
            args.push(codec::arg(1, v));
        }
        let data = self.client.invoke("UI", "Panel_AddInputField", &args).await?;
        Decode::decode_krpc(&self.client, &data)
    }

    /// Streamed variant of `add_input_field`: the server pushes the value
    /// at the stream's update rate instead of being polled.
    pub async fn add_input_field_stream(&self, visible: Option<bool>) -> crate::Result<crate::Stream<InputField>> {
        let mut args = vec![codec::arg(0, &self.id)];
        if let Some(v) = &visible {
            args.push(codec::arg(1, v));
        }
        self.client.stream("UI", "Panel_AddInputField", &args).await
    }

    /// Add a button to the panel.
    ///
    /// # Arguments
    ///
    /// * `content` - The label for the button.
    /// * `visible` - Whether the button is visible.
    pub async fn add_button(&self, content: &str, visible: Option<bool>) -> crate::Result<Button> {
        let mut args = vec![codec::arg(0, &self.id), codec::arg(1, &content)];
        if let Some(v) = &visible {
            args.push(codec::arg(2, v));
        }
        let data = self.client.invoke("UI", "Panel_AddButton", &args).await?;
        Decode::decode_krpc(&self.client, &data)
    }

    /// Streamed variant of `add_button`: the server pushes the value
    /// at the stream's update rate instead of being polled.
    pub async fn add_button_stream(&self, content: &str, visible: Option<bool>) -> crate::Result<crate::Stream<Button>> {
        let mut args = vec![codec::arg(0, &self.id), codec::arg(1, &content)];
        if let Some(v) = &visible {
            args.push(codec::arg(2, v));
        }
        self.client.stream("UI", "Panel_AddButton", &args).await
    }

    /// Remove the UI object.
    pub async fn remove(&self) -> crate::Result<()> {
        self.client.invoke("UI", "Panel_Remove", &[codec::arg(0, &self.id)]).await?;
        Ok(())
    }
}

impl PartialEq for Panel {
    fn eq(&self, other: &Self) -> bool {
        self.id == other.id
    }
}

impl Eq for Panel {}

impl std::hash::Hash for Panel {
    fn hash<H: std::hash::Hasher>(&self, state: &mut H) {
        self.id.hash(state);
    }
}

impl Encode for Panel {
    fn encode_krpc(&self) -> Vec<u8> {
        self.id.encode_krpc()
    }
}

impl Decode for Panel {
    fn decode_krpc(client: &crate::ClientRef, bytes: &[u8]) -> crate::Result<Self> {
        let id = <u64 as Decode>::decode_krpc(client, bytes)?;
        Ok(Self::new(client.clone(), id))
    }
}

impl Decode for Option<Panel> {
    fn decode_krpc(client: &crate::ClientRef, bytes: &[u8]) -> crate::Result<Self> {
        let id = <u64 as Decode>::decode_krpc(client, bytes)?;
        Ok(if id == 0 { None } else { Some(Panel::new(client.clone(), id)) })
    }
}

/// A Unity engine Rect Transform for a UI object. See the [Unity manual](https://docs.unity3d.com/Manual/class-RectTransform.html) for more details.
///
/// A remote object handle for a `UI.RectTransform` instance.
#[derive(Debug, Clone)]
pub struct RectTransform {
    client: crate::ClientRef,
    pub(crate) id: u64,
}

impl RectTransform {
    pub(crate) fn new(client: crate::ClientRef, id: u64) -> Self {
        Self { client, id }
    }

    /// The anchor point for the lower left corner of the rectangle defined as a fraction of the size of the parent rectangle.
    pub async fn anchor_max(&self) -> crate::Result<(f64, f64)> {
        let data = self.client.invoke("UI", "RectTransform_get_AnchorMax", &[codec::arg(0, &self.id)]).await?;
        Decode::decode_krpc(&self.client, &data)
    }

    /// Streamed variant of `anchor_max`: the server pushes the value
    /// at the stream's update rate instead of being polled.
    pub async fn anchor_max_stream(&self) -> crate::Result<crate::Stream<(f64, f64)>> {
        self.client.stream("UI", "RectTransform_get_AnchorMax", &[codec::arg(0, &self.id)]).await
    }

    /// The anchor point for the upper right corner of the rectangle defined as a fraction of the size of the parent rectangle.
    pub async fn anchor_min(&self) -> crate::Result<(f64, f64)> {
        let data = self.client.invoke("UI", "RectTransform_get_AnchorMin", &[codec::arg(0, &self.id)]).await?;
        Decode::decode_krpc(&self.client, &data)
    }

    /// Streamed variant of `anchor_min`: the server pushes the value
    /// at the stream's update rate instead of being polled.
    pub async fn anchor_min_stream(&self) -> crate::Result<crate::Stream<(f64, f64)>> {
        self.client.stream("UI", "RectTransform_get_AnchorMin", &[codec::arg(0, &self.id)]).await
    }

    /// Position of the rectangles pivot point relative to the anchors.
    pub async fn local_position(&self) -> crate::Result<(f64, f64, f64)> {
        let data = self.client.invoke("UI", "RectTransform_get_LocalPosition", &[codec::arg(0, &self.id)]).await?;
        Decode::decode_krpc(&self.client, &data)
    }

    /// Streamed variant of `local_position`: the server pushes the value
    /// at the stream's update rate instead of being polled.
    pub async fn local_position_stream(&self) -> crate::Result<crate::Stream<(f64, f64, f64)>> {
        self.client.stream("UI", "RectTransform_get_LocalPosition", &[codec::arg(0, &self.id)]).await
    }

    /// Position of the rectangles lower left corner relative to the anchors.
    pub async fn lower_left(&self) -> crate::Result<(f64, f64)> {
        let data = self.client.invoke("UI", "RectTransform_get_LowerLeft", &[codec::arg(0, &self.id)]).await?;
        Decode::decode_krpc(&self.client, &data)
    }

    /// Streamed variant of `lower_left`: the server pushes the value
    /// at the stream's update rate instead of being polled.
    pub async fn lower_left_stream(&self) -> crate::Result<crate::Stream<(f64, f64)>> {
        self.client.stream("UI", "RectTransform_get_LowerLeft", &[codec::arg(0, &self.id)]).await
    }

    /// Location of the pivot point around which the rectangle rotates, defined as a fraction of the size of the rectangle itself.
    pub async fn pivot(&self) -> crate::Result<(f64, f64)> {
        let data = self.client.invoke("UI", "RectTransform_get_Pivot", &[codec::arg(0, &self.id)]).await?;
        Decode::decode_krpc(&self.client, &data)
    }

    /// Streamed variant of `pivot`: the server pushes the value
    /// at the stream's update rate instead of being polled.
    pub async fn pivot_stream(&self) -> crate::Result<crate::Stream<(f64, f64)>> {
        self.client.stream("UI", "RectTransform_get_Pivot", &[codec::arg(0, &self.id)]).await
    }

    /// Position of the rectangles pivot point relative to the anchors.
    pub async fn position(&self) -> crate::Result<(f64, f64)> {
        let data = self.client.invoke("UI", "RectTransform_get_Position", &[codec::arg(0, &self.id)]).await?;
        Decode::decode_krpc(&self.client, &data)
    }

    /// Streamed variant of `position`: the server pushes the value
    /// at the stream's update rate instead of being polled.
    pub async fn position_stream(&self) -> crate::Result<crate::Stream<(f64, f64)>> {
        self.client.stream("UI", "RectTransform_get_Position", &[codec::arg(0, &self.id)]).await
    }

    /// Rotation, as a quaternion, of the object around its pivot point.
    pub async fn rotation(&self) -> crate::Result<(f64, f64, f64, f64)> {
        let data = self.client.invoke("UI", "RectTransform_get_Rotation", &[codec::arg(0, &self.id)]).await?;
        Decode::decode_krpc(&self.client, &data)
    }

    /// Streamed variant of `rotation`: the server pushes the value
    /// at the stream's update rate instead of being polled.
    pub async fn rotation_stream(&self) -> crate::Result<crate::Stream<(f64, f64, f64, f64)>> {
        self.client.stream("UI", "RectTransform_get_Rotation", &[codec::arg(0, &self.id)]).await
    }

    /// Scale factor applied to the object in the x, y and z dimensions.
    pub async fn scale(&self) -> crate::Result<(f64, f64, f64)> {
        let data = self.client.invoke("UI", "RectTransform_get_Scale", &[codec::arg(0, &self.id)]).await?;
        Decode::decode_krpc(&self.client, &data)
    }

    /// Streamed variant of `scale`: the server pushes the value
    /// at the stream's update rate instead of being polled.
    pub async fn scale_stream(&self) -> crate::Result<crate::Stream<(f64, f64, f64)>> {
        self.client.stream("UI", "RectTransform_get_Scale", &[codec::arg(0, &self.id)]).await
    }

    /// Width and height of the rectangle.
    pub async fn size(&self) -> crate::Result<(f64, f64)> {
        let data = self.client.invoke("UI", "RectTransform_get_Size", &[codec::arg(0, &self.id)]).await?;
        Decode::decode_krpc(&self.client, &data)
    }

    /// Streamed variant of `size`: the server pushes the value
    /// at the stream's update rate instead of being polled.
    pub async fn size_stream(&self) -> crate::Result<crate::Stream<(f64, f64)>> {
        self.client.stream("UI", "RectTransform_get_Size", &[codec::arg(0, &self.id)]).await
    }

    /// Position of the rectangles upper right corner relative to the anchors.
    pub async fn upper_right(&self) -> crate::Result<(f64, f64)> {
        let data = self.client.invoke("UI", "RectTransform_get_UpperRight", &[codec::arg(0, &self.id)]).await?;
        Decode::decode_krpc(&self.client, &data)
    }

    /// Streamed variant of `upper_right`: the server pushes the value
    /// at the stream's update rate instead of being polled.
    pub async fn upper_right_stream(&self) -> crate::Result<crate::Stream<(f64, f64)>> {
        self.client.stream("UI", "RectTransform_get_UpperRight", &[codec::arg(0, &self.id)]).await
    }

    /// Set the minimum and maximum anchor points as a fraction of the size of the parent rectangle.
    pub async fn set_anchor(&self, value: (f64, f64)) -> crate::Result<()> {
        self.client.invoke("UI", "RectTransform_set_Anchor", &[codec::arg(0, &self.id), codec::arg(1, &value)]).await?;
        Ok(())
    }

    /// The anchor point for the lower left corner of the rectangle defined as a fraction of the size of the parent rectangle.
    pub async fn set_anchor_max(&self, value: (f64, f64)) -> crate::Result<()> {
        self.client.invoke("UI", "RectTransform_set_AnchorMax", &[codec::arg(0, &self.id), codec::arg(1, &value)]).await?;
        Ok(())
    }

    /// The anchor point for the upper right corner of the rectangle defined as a fraction of the size of the parent rectangle.
    pub async fn set_anchor_min(&self, value: (f64, f64)) -> crate::Result<()> {
        self.client.invoke("UI", "RectTransform_set_AnchorMin", &[codec::arg(0, &self.id), codec::arg(1, &value)]).await?;
        Ok(())
    }

    /// Position of the rectangles pivot point relative to the anchors.
    pub async fn set_local_position(&self, value: (f64, f64, f64)) -> crate::Result<()> {
        self.client.invoke("UI", "RectTransform_set_LocalPosition", &[codec::arg(0, &self.id), codec::arg(1, &value)]).await?;
        Ok(())
    }

    /// Position of the rectangles lower left corner relative to the anchors.
    pub async fn set_lower_left(&self, value: (f64, f64)) -> crate::Result<()> {
        self.client.invoke("UI", "RectTransform_set_LowerLeft", &[codec::arg(0, &self.id), codec::arg(1, &value)]).await?;
        Ok(())
    }

    /// Location of the pivot point around which the rectangle rotates, defined as a fraction of the size of the rectangle itself.
    pub async fn set_pivot(&self, value: (f64, f64)) -> crate::Result<()> {
        self.client.invoke("UI", "RectTransform_set_Pivot", &[codec::arg(0, &self.id), codec::arg(1, &value)]).await?;
        Ok(())
    }

    /// Position of the rectangles pivot point relative to the anchors.
    pub async fn set_position(&self, value: (f64, f64)) -> crate::Result<()> {
        self.client.invoke("UI", "RectTransform_set_Position", &[codec::arg(0, &self.id), codec::arg(1, &value)]).await?;
        Ok(())
    }

    /// Rotation, as a quaternion, of the object around its pivot point.
    pub async fn set_rotation(&self, value: (f64, f64, f64, f64)) -> crate::Result<()> {
        self.client.invoke("UI", "RectTransform_set_Rotation", &[codec::arg(0, &self.id), codec::arg(1, &value)]).await?;
        Ok(())
    }

    /// Scale factor applied to the object in the x, y and z dimensions.
    pub async fn set_scale(&self, value: (f64, f64, f64)) -> crate::Result<()> {
        self.client.invoke("UI", "RectTransform_set_Scale", &[codec::arg(0, &self.id), codec::arg(1, &value)]).await?;
        Ok(())
    }

    /// Width and height of the rectangle.
    pub async fn set_size(&self, value: (f64, f64)) -> crate::Result<()> {
        self.client.invoke("UI", "RectTransform_set_Size", &[codec::arg(0, &self.id), codec::arg(1, &value)]).await?;
        Ok(())
    }

    /// Position of the rectangles upper right corner relative to the anchors.
    pub async fn set_upper_right(&self, value: (f64, f64)) -> crate::Result<()> {
        self.client.invoke("UI", "RectTransform_set_UpperRight", &[codec::arg(0, &self.id), codec::arg(1, &value)]).await?;
        Ok(())
    }
}

impl PartialEq for RectTransform {
    fn eq(&self, other: &Self) -> bool {
        self.id == other.id
    }
}

impl Eq for RectTransform {}

impl std::hash::Hash for RectTransform {
    fn hash<H: std::hash::Hasher>(&self, state: &mut H) {
        self.id.hash(state);
    }
}

impl Encode for RectTransform {
    fn encode_krpc(&self) -> Vec<u8> {
        self.id.encode_krpc()
    }
}

impl Decode for RectTransform {
    fn decode_krpc(client: &crate::ClientRef, bytes: &[u8]) -> crate::Result<Self> {
        let id = <u64 as Decode>::decode_krpc(client, bytes)?;
        Ok(Self::new(client.clone(), id))
    }
}

impl Decode for Option<RectTransform> {
    fn decode_krpc(client: &crate::ClientRef, bytes: &[u8]) -> crate::Result<Self> {
        let id = <u64 as Decode>::decode_krpc(client, bytes)?;
        Ok(if id == 0 { None } else { Some(RectTransform::new(client.clone(), id)) })
    }
}

/// A text label. See `UI.Panel.AddText`.
///
/// A remote object handle for a `UI.Text` instance.
#[derive(Debug, Clone)]
pub struct Text {
    client: crate::ClientRef,
    pub(crate) id: u64,
}

impl Text {
    pub(crate) fn new(client: crate::ClientRef, id: u64) -> Self {
        Self { client, id }
    }

    /// Alignment.
    pub async fn alignment(&self) -> crate::Result<TextAnchor> {
        let data = self.client.invoke("UI", "Text_get_Alignment", &[codec::arg(0, &self.id)]).await?;
        Decode::decode_krpc(&self.client, &data)
    }

    /// Streamed variant of `alignment`: the server pushes the value
    /// at the stream's update rate instead of being polled.
    pub async fn alignment_stream(&self) -> crate::Result<crate::Stream<TextAnchor>> {
        self.client.stream("UI", "Text_get_Alignment", &[codec::arg(0, &self.id)]).await
    }

    /// A list of all available fonts.
    pub async fn available_fonts(&self) -> crate::Result<Vec<String>> {
        let data = self.client.invoke("UI", "Text_get_AvailableFonts", &[codec::arg(0, &self.id)]).await?;
        Decode::decode_krpc(&self.client, &data)
    }

    /// Streamed variant of `available_fonts`: the server pushes the value
    /// at the stream's update rate instead of being polled.
    pub async fn available_fonts_stream(&self) -> crate::Result<crate::Stream<Vec<String>>> {
        self.client.stream("UI", "Text_get_AvailableFonts", &[codec::arg(0, &self.id)]).await
    }

    /// Set the color
    pub async fn color(&self) -> crate::Result<(f64, f64, f64)> {
        let data = self.client.invoke("UI", "Text_get_Color", &[codec::arg(0, &self.id)]).await?;
        Decode::decode_krpc(&self.client, &data)
    }

    /// Streamed variant of `color`: the server pushes the value
    /// at the stream's update rate instead of being polled.
    pub async fn color_stream(&self) -> crate::Result<crate::Stream<(f64, f64, f64)>> {
        self.client.stream("UI", "Text_get_Color", &[codec::arg(0, &self.id)]).await
    }

    /// The text string
    pub async fn content(&self) -> crate::Result<String> {
        let data = self.client.invoke("UI", "Text_get_Content", &[codec::arg(0, &self.id)]).await?;
        Decode::decode_krpc(&self.client, &data)
    }

    /// Streamed variant of `content`: the server pushes the value
    /// at the stream's update rate instead of being polled.
    pub async fn content_stream(&self) -> crate::Result<crate::Stream<String>> {
        self.client.stream("UI", "Text_get_Content", &[codec::arg(0, &self.id)]).await
    }

    /// Name of the font
    pub async fn font(&self) -> crate::Result<String> {
        let data = self.client.invoke("UI", "Text_get_Font", &[codec::arg(0, &self.id)]).await?;
        Decode::decode_krpc(&self.client, &data)
    }

    /// Streamed variant of `font`: the server pushes the value
    /// at the stream's update rate instead of being polled.
    pub async fn font_stream(&self) -> crate::Result<crate::Stream<String>> {
        self.client.stream("UI", "Text_get_Font", &[codec::arg(0, &self.id)]).await
    }

    /// Line spacing.
    pub async fn line_spacing(&self) -> crate::Result<f32> {
        let data = self.client.invoke("UI", "Text_get_LineSpacing", &[codec::arg(0, &self.id)]).await?;
        Decode::decode_krpc(&self.client, &data)
    }

    /// Streamed variant of `line_spacing`: the server pushes the value
    /// at the stream's update rate instead of being polled.
    pub async fn line_spacing_stream(&self) -> crate::Result<crate::Stream<f32>> {
        self.client.stream("UI", "Text_get_LineSpacing", &[codec::arg(0, &self.id)]).await
    }

    /// The rect transform for the text.
    pub async fn rect_transform(&self) -> crate::Result<RectTransform> {
        let data = self.client.invoke("UI", "Text_get_RectTransform", &[codec::arg(0, &self.id)]).await?;
        Decode::decode_krpc(&self.client, &data)
    }

    /// Streamed variant of `rect_transform`: the server pushes the value
    /// at the stream's update rate instead of being polled.
    pub async fn rect_transform_stream(&self) -> crate::Result<crate::Stream<RectTransform>> {
        self.client.stream("UI", "Text_get_RectTransform", &[codec::arg(0, &self.id)]).await
    }

    /// Font size.
    pub async fn size(&self) -> crate::Result<i32> {
        let data = self.client.invoke("UI", "Text_get_Size", &[codec::arg(0, &self.id)]).await?;
        Decode::decode_krpc(&self.client, &data)
    }

    /// Streamed variant of `size`: the server pushes the value
    /// at the stream's update rate instead of being polled.
    pub async fn size_stream(&self) -> crate::Result<crate::Stream<i32>> {
        self.client.stream("UI", "Text_get_Size", &[codec::arg(0, &self.id)]).await
    }

    /// Font style.
    pub async fn style(&self) -> crate::Result<FontStyle> {
        let data = self.client.invoke("UI", "Text_get_Style", &[codec::arg(0, &self.id)]).await?;
        Decode::decode_krpc(&self.client, &data)
    }

    /// Streamed variant of `style`: the server pushes the value
    /// at the stream's update rate instead of being polled.
    pub async fn style_stream(&self) -> crate::Result<crate::Stream<FontStyle>> {
        self.client.stream("UI", "Text_get_Style", &[codec::arg(0, &self.id)]).await
    }

    /// Whether the UI object is visible.
    pub async fn visible(&self) -> crate::Result<bool> {
        let data = self.client.invoke("UI", "Text_get_Visible", &[codec::arg(0, &self.id)]).await?;
        Decode::decode_krpc(&self.client, &data)
    }

    /// Streamed variant of `visible`: the server pushes the value
    /// at the stream's update rate instead of being polled.
    pub async fn visible_stream(&self) -> crate::Result<crate::Stream<bool>> {
        self.client.stream("UI", "Text_get_Visible", &[codec::arg(0, &self.id)]).await
    }

    /// Alignment.
    pub async fn set_alignment(&self, value: TextAnchor) -> crate::Result<()> {
        self.client.invoke("UI", "Text_set_Alignment", &[codec::arg(0, &self.id), codec::arg(1, &value)]).await?;
        Ok(())
    }

    /// Set the color
    pub async fn set_color(&self, value: (f64, f64, f64)) -> crate::Result<()> {
        self.client.invoke("UI", "Text_set_Color", &[codec::arg(0, &self.id), codec::arg(1, &value)]).await?;
        Ok(())
    }

    /// The text string
    pub async fn set_content(&self, value: &str) -> crate::Result<()> {
        self.client.invoke("UI", "Text_set_Content", &[codec::arg(0, &self.id), codec::arg(1, &value)]).await?;
        Ok(())
    }

    /// Name of the font
    pub async fn set_font(&self, value: &str) -> crate::Result<()> {
        self.client.invoke("UI", "Text_set_Font", &[codec::arg(0, &self.id), codec::arg(1, &value)]).await?;
        Ok(())
    }

    /// Line spacing.
    pub async fn set_line_spacing(&self, value: f32) -> crate::Result<()> {
        self.client.invoke("UI", "Text_set_LineSpacing", &[codec::arg(0, &self.id), codec::arg(1, &value)]).await?;
        Ok(())
    }

    /// Font size.
    pub async fn set_size(&self, value: i32) -> crate::Result<()> {
        self.client.invoke("UI", "Text_set_Size", &[codec::arg(0, &self.id), codec::arg(1, &value)]).await?;
        Ok(())
    }

    /// Font style.
    pub async fn set_style(&self, value: FontStyle) -> crate::Result<()> {
        self.client.invoke("UI", "Text_set_Style", &[codec::arg(0, &self.id), codec::arg(1, &value)]).await?;
        Ok(())
    }

    /// Whether the UI object is visible.
    pub async fn set_visible(&self, value: bool) -> crate::Result<()> {
        self.client.invoke("UI", "Text_set_Visible", &[codec::arg(0, &self.id), codec::arg(1, &value)]).await?;
        Ok(())
    }

    /// Remove the UI object.
    pub async fn remove(&self) -> crate::Result<()> {
        self.client.invoke("UI", "Text_Remove", &[codec::arg(0, &self.id)]).await?;
        Ok(())
    }
}

impl PartialEq for Text {
    fn eq(&self, other: &Self) -> bool {
        self.id == other.id
    }
}

impl Eq for Text {}

impl std::hash::Hash for Text {
    fn hash<H: std::hash::Hasher>(&self, state: &mut H) {
        self.id.hash(state);
    }
}

impl Encode for Text {
    fn encode_krpc(&self) -> Vec<u8> {
        self.id.encode_krpc()
    }
}

impl Decode for Text {
    fn decode_krpc(client: &crate::ClientRef, bytes: &[u8]) -> crate::Result<Self> {
        let id = <u64 as Decode>::decode_krpc(client, bytes)?;
        Ok(Self::new(client.clone(), id))
    }
}

impl Decode for Option<Text> {
    fn decode_krpc(client: &crate::ClientRef, bytes: &[u8]) -> crate::Result<Self> {
        let id = <u64 as Decode>::decode_krpc(client, bytes)?;
        Ok(if id == 0 { None } else { Some(Text::new(client.clone(), id)) })
    }
}

/// Provides functionality for drawing and interacting with in-game user interface elements.
///
/// For drawing 3D objects in the flight scene, see the Drawing service.
pub struct UI {
    client: crate::ClientRef,
}

impl UI {
    pub fn new(client: crate::ClientRef) -> Self {
        Self { client }
    }

    /// The stock UI canvas.
    pub async fn stock_canvas(&self) -> crate::Result<Canvas> {
        let data = self.client.invoke("UI", "get_StockCanvas", &[]).await?;
        Decode::decode_krpc(&self.client, &data)
    }

    /// Streamed variant of `stock_canvas`: the server pushes the value
    /// at the stream's update rate instead of being polled.
    pub async fn stock_canvas_stream(&self) -> crate::Result<crate::Stream<Canvas>> {
        self.client.stream("UI", "get_StockCanvas", &[]).await
    }

    /// Add a new canvas.
    ///
    /// If you want to add UI elements to KSPs stock UI canvas, use `UI.StockCanvas`.
    pub async fn add_canvas(&self) -> crate::Result<Canvas> {
        let data = self.client.invoke("UI", "AddCanvas", &[]).await?;
        Decode::decode_krpc(&self.client, &data)
    }

    /// Streamed variant of `add_canvas`: the server pushes the value
    /// at the stream's update rate instead of being polled.
    pub async fn add_canvas_stream(&self) -> crate::Result<crate::Stream<Canvas>> {
        self.client.stream("UI", "AddCanvas", &[]).await
    }

    /// Display a message on the screen.
    ///
    /// The message appears just like a stock message, for example quicksave or quickload messages.
    ///
    /// # Arguments
    ///
    /// * `content` - Message content.
    /// * `duration` - Duration before the message disappears, in seconds.
    /// * `position` - Position to display the message.
    /// * `size` - Size of the message, differs per position.
    /// * `color` - The color of the message.
    pub async fn message(&self, content: &str, duration: Option<f32>, position: Option<MessagePosition>, color: Option<(f64, f64, f64)>, size: Option<f32>) -> crate::Result<()> {
        let mut args = vec![codec::arg(0, &content)];
        if let Some(v) = &duration {
            args.push(codec::arg(1, v));
        }
        if let Some(v) = &position {
            args.push(codec::arg(2, v));
        }
        if let Some(v) = &color {
            args.push(codec::arg(3, v));
        }
        if let Some(v) = &size {
            args.push(codec::arg(4, v));
        }
        self.client.invoke("UI", "Message", &args).await?;
        Ok(())
    }

    /// Remove all user interface elements.
    ///
    /// # Arguments
    ///
    /// * `client_only` - If true, only remove objects created by the calling client.
    pub async fn clear(&self, client_only: Option<bool>) -> crate::Result<()> {
        let mut args = vec![];
        if let Some(v) = &client_only {
            args.push(codec::arg(0, v));
        }
        self.client.invoke("UI", "Clear", &args).await?;
        Ok(())
    }
}
